// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { EmotionEmbeddingItem } from "./EmotionEmbeddingItem.mjs";
export const EmotionEmbedding = core.serialization.list(EmotionEmbeddingItem);
