// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { SentimentItem } from "./SentimentItem.mjs";
export const Sentiment = core.serialization.list(SentimentItem);
