"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AudioFormatType = void 0;
exports.AudioFormatType = {
    Mp3: "mp3",
    Pcm: "pcm",
    Wav: "wav",
};
