"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TimestampType = void 0;
exports.TimestampType = {
    Word: "word",
    Phoneme: "phoneme",
};
