// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../core/index.mjs";
export const PostedPromptVersion = core.serialization.object({
    text: core.serialization.string(),
    versionDescription: core.serialization.property("version_description", core.serialization.string().optional()),
});
