// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../../core/index.mjs";
import { SubscribeEvent } from "../../types/SubscribeEvent.mjs";
export const StreamSocketResponse = core.serialization.undiscriminatedUnion([SubscribeEvent]);
