// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { Inference } from "./Inference.mjs";
export const AssistantProsody = core.serialization.object({
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    id: core.serialization.string().optional(),
    models: Inference,
    type: core.serialization.stringLiteral("assistant_prosody"),
});
