// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ChatMessage } from "./ChatMessage.mjs";
import { Inference } from "./Inference.mjs";
export const AssistantMessage = core.serialization.object({
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    fromText: core.serialization.property("from_text", core.serialization.boolean()),
    id: core.serialization.string().optional(),
    language: core.serialization.string().optional(),
    message: ChatMessage,
    models: Inference,
    type: core.serialization.stringLiteral("assistant_message"),
});
