// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const AssistantInput = core.serialization.object({
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    text: core.serialization.string(),
    type: core.serialization.stringLiteral("assistant_input"),
});
