// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { Encoding } from "./Encoding.mjs";
export const AudioConfiguration = core.serialization.object({
    channels: core.serialization.number(),
    codec: core.serialization.string().optional(),
    encoding: Encoding,
    sampleRate: core.serialization.property("sample_rate", core.serialization.number()),
});
