// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { BuiltInTool } from "./BuiltInTool.mjs";
export const BuiltinToolConfig = core.serialization.object({
    fallbackContent: core.serialization.property("fallback_content", core.serialization.string().optional()),
    name: BuiltInTool,
});
