// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ToolErrorMessage } from "./ToolErrorMessage.mjs";
import { ToolResponseMessage } from "./ToolResponseMessage.mjs";
export const ChatMessageToolResult = core.serialization.undiscriminatedUnion([ToolResponseMessage, ToolErrorMessage]);
