// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ChatMessageToolResult } from "./ChatMessageToolResult.mjs";
import { Role } from "./Role.mjs";
import { ToolCallMessage } from "./ToolCallMessage.mjs";
export const ChatMessage = core.serialization.object({
    content: core.serialization.string().optional(),
    role: Role,
    toolCall: core.serialization.property("tool_call", ToolCallMessage.optional()),
    toolResult: core.serialization.property("tool_result", ChatMessageToolResult.optional()),
});
