// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const ChatMetadata = core.serialization.object({
    chatGroupId: core.serialization.property("chat_group_id", core.serialization.string()),
    chatId: core.serialization.property("chat_id", core.serialization.string()),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    requestId: core.serialization.property("request_id", core.serialization.string().optional()),
    type: core.serialization.stringLiteral("chat_metadata"),
});
