// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ContextType } from "./ContextType.mjs";
export const ConnectSessionSettingsContext = core.serialization.object({
    text: core.serialization.string().optional(),
    type: ContextType.optional(),
});
