// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { Encoding } from "./Encoding.mjs";
export const ConnectSessionSettingsAudio = core.serialization.object({
    channels: core.serialization.number().optional(),
    encoding: Encoding.optional(),
    sampleRate: core.serialization.property("sample_rate", core.serialization.number().optional()),
});
