// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ContextType } from "./ContextType.mjs";
export const Context = core.serialization.object({
    text: core.serialization.string(),
    type: ContextType.optional(),
});
