// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { AssistantInput } from "./AssistantInput.mjs";
import { PauseAssistantMessage } from "./PauseAssistantMessage.mjs";
import { ResumeAssistantMessage } from "./ResumeAssistantMessage.mjs";
import { SessionSettings } from "./SessionSettings.mjs";
import { ToolErrorMessage } from "./ToolErrorMessage.mjs";
import { ToolResponseMessage } from "./ToolResponseMessage.mjs";
import { UserInput } from "./UserInput.mjs";
export const ControlPlanePublishEvent = core.serialization.undiscriminatedUnion([
    SessionSettings,
    UserInput,
    AssistantInput,
    ToolResponseMessage,
    ToolErrorMessage,
    PauseAssistantMessage,
    ResumeAssistantMessage,
]);
