// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const ErrorResponse = core.serialization.object({
    code: core.serialization.string().optional(),
    error: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});
