// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ProsodyInference } from "./ProsodyInference.mjs";
export const Inference = core.serialization.object({
    prosody: ProsodyInference.optional(),
});
