// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const PostedConfigPromptSpec = core.serialization.object({
    id: core.serialization.string().optional(),
    text: core.serialization.string().optional(),
    version: core.serialization.number().optional(),
});
