// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { PostedBuiltinToolName } from "./PostedBuiltinToolName.mjs";
export const PostedBuiltinTool = core.serialization.object({
    fallbackContent: core.serialization.property("fallback_content", core.serialization.string().optional()),
    name: PostedBuiltinToolName,
});
