// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { PostedWebhookEventType } from "./PostedWebhookEventType.mjs";
export const PostedWebhookSpec = core.serialization.object({
    events: core.serialization.list(PostedWebhookEventType),
    url: core.serialization.string(),
});
