// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { PostedEventMessageSpec } from "./PostedEventMessageSpec.mjs";
export const PostedEventMessageSpecs = core.serialization.object({
    onInactivityTimeout: core.serialization.property("on_inactivity_timeout", PostedEventMessageSpec.optional()),
    onMaxDurationTimeout: core.serialization.property("on_max_duration_timeout", PostedEventMessageSpec.optional()),
    onNewChat: core.serialization.property("on_new_chat", PostedEventMessageSpec.optional()),
});
