// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { LanguageModelType } from "./LanguageModelType.mjs";
import { ModelProviderEnum } from "./ModelProviderEnum.mjs";
export const PostedLanguageModel = core.serialization.object({
    modelProvider: core.serialization.property("model_provider", ModelProviderEnum.optional()),
    modelResource: core.serialization.property("model_resource", LanguageModelType.optional()),
    temperature: core.serialization.number().optional(),
});
