// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { EmotionScores } from "./EmotionScores.mjs";
export const ProsodyInference = core.serialization.object({
    scores: EmotionScores,
});
