// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnChatEvent } from "./ReturnChatEvent.mjs";
import { ReturnChatGroupPagedEventsPaginationDirection } from "./ReturnChatGroupPagedEventsPaginationDirection.mjs";
export const ReturnChatGroupPagedEvents = core.serialization.object({
    eventsPage: core.serialization.property("events_page", core.serialization.list(ReturnChatEvent)),
    id: core.serialization.string(),
    pageNumber: core.serialization.property("page_number", core.serialization.number()),
    pageSize: core.serialization.property("page_size", core.serialization.number()),
    paginationDirection: core.serialization.property("pagination_direction", ReturnChatGroupPagedEventsPaginationDirection),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});
