// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnEventMessageSpec } from "./ReturnEventMessageSpec.mjs";
export const ReturnEventMessageSpecs = core.serialization.object({
    onInactivityTimeout: core.serialization.property("on_inactivity_timeout", ReturnEventMessageSpec.optional()),
    onMaxDurationTimeout: core.serialization.property("on_max_duration_timeout", ReturnEventMessageSpec.optional()),
    onNewChat: core.serialization.property("on_new_chat", ReturnEventMessageSpec.optional()),
});
