// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnChatEventRole } from "./ReturnChatEventRole.mjs";
import { ReturnChatEventType } from "./ReturnChatEventType.mjs";
export const ReturnChatEvent = core.serialization.object({
    chatId: core.serialization.property("chat_id", core.serialization.string()),
    emotionFeatures: core.serialization.property("emotion_features", core.serialization.string().optional()),
    id: core.serialization.string(),
    messageText: core.serialization.property("message_text", core.serialization.string().optional()),
    metadata: core.serialization.string().optional(),
    relatedEventId: core.serialization.property("related_event_id", core.serialization.string().optional()),
    role: ReturnChatEventRole,
    timestamp: core.serialization.number(),
    type: ReturnChatEventType,
});
