// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnChat } from "./ReturnChat.mjs";
import { ReturnPagedChatsPaginationDirection } from "./ReturnPagedChatsPaginationDirection.mjs";
export const ReturnPagedChats = core.serialization.object({
    chatsPage: core.serialization.property("chats_page", core.serialization.list(ReturnChat)),
    pageNumber: core.serialization.property("page_number", core.serialization.number()),
    pageSize: core.serialization.property("page_size", core.serialization.number()),
    paginationDirection: core.serialization.property("pagination_direction", ReturnPagedChatsPaginationDirection),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});
