// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnUserDefinedTool } from "./ReturnUserDefinedTool.mjs";
export const ReturnPagedUserDefinedTools = core.serialization.object({
    pageNumber: core.serialization.property("page_number", core.serialization.number()),
    pageSize: core.serialization.property("page_size", core.serialization.number()),
    toolsPage: core.serialization.property("tools_page", core.serialization.list(ReturnUserDefinedTool.optional())),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});
