// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnChatStatus } from "./ReturnChatStatus.mjs";
import { ReturnConfigSpec } from "./ReturnConfigSpec.mjs";
export const ReturnChat = core.serialization.object({
    chatGroupId: core.serialization.property("chat_group_id", core.serialization.string()),
    config: ReturnConfigSpec.optional(),
    endTimestamp: core.serialization.property("end_timestamp", core.serialization.number().optional()),
    eventCount: core.serialization.property("event_count", core.serialization.number().optional()),
    id: core.serialization.string(),
    metadata: core.serialization.string().optional(),
    startTimestamp: core.serialization.property("start_timestamp", core.serialization.number()),
    status: ReturnChatStatus,
});
