// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnBuiltinToolToolType } from "./ReturnBuiltinToolToolType.mjs";
export const ReturnBuiltinTool = core.serialization.object({
    fallbackContent: core.serialization.property("fallback_content", core.serialization.string().optional()),
    name: core.serialization.string(),
    toolType: core.serialization.property("tool_type", ReturnBuiltinToolToolType),
});
