// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const ReturnPromptVersionType = core.serialization.enum_(["FIXED", "LATEST"]);
