// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnConfigSpec } from "./ReturnConfigSpec.mjs";
export const ReturnChatGroup = core.serialization.object({
    active: core.serialization.boolean().optional(),
    firstStartTimestamp: core.serialization.property("first_start_timestamp", core.serialization.number()),
    id: core.serialization.string(),
    mostRecentChatId: core.serialization.property("most_recent_chat_id", core.serialization.string().optional()),
    mostRecentConfig: core.serialization.property("most_recent_config", ReturnConfigSpec.optional()),
    mostRecentStartTimestamp: core.serialization.property("most_recent_start_timestamp", core.serialization.number()),
    numChats: core.serialization.property("num_chats", core.serialization.number()),
});
