// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnConfig } from "./ReturnConfig.mjs";
export const ReturnPagedConfigs = core.serialization.object({
    configsPage: core.serialization.property("configs_page", core.serialization.list(ReturnConfig).optional()),
    pageNumber: core.serialization.property("page_number", core.serialization.number().optional()),
    pageSize: core.serialization.property("page_size", core.serialization.number().optional()),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});
