// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnChatAudioReconstructionStatus } from "./ReturnChatAudioReconstructionStatus.mjs";
export const ReturnChatAudioReconstruction = core.serialization.object({
    filename: core.serialization.string().optional(),
    id: core.serialization.string(),
    modifiedAt: core.serialization.property("modified_at", core.serialization.number().optional()),
    signedAudioUrl: core.serialization.property("signed_audio_url", core.serialization.string().optional()),
    signedUrlExpirationTimestampMillis: core.serialization.property("signed_url_expiration_timestamp_millis", core.serialization.number().optional()),
    status: ReturnChatAudioReconstructionStatus,
    userId: core.serialization.property("user_id", core.serialization.string()),
});
