// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const ReturnPrompt = core.serialization.object({
    createdOn: core.serialization.property("created_on", core.serialization.number()),
    id: core.serialization.string(),
    modifiedOn: core.serialization.property("modified_on", core.serialization.number()),
    name: core.serialization.string(),
    text: core.serialization.string(),
    version: core.serialization.number(),
    versionDescription: core.serialization.property("version_description", core.serialization.string().optional()),
    versionType: core.serialization.property("version_type", core.serialization.string()),
});
