// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const ReturnChatGroupPagedAudioReconstructionsPaginationDirection = core.serialization.enum_(["ASC", "DESC"]);
