// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnWebhookEventType } from "./ReturnWebhookEventType.mjs";
export const ReturnWebhookSpec = core.serialization.object({
    events: core.serialization.list(ReturnWebhookEventType),
    url: core.serialization.string(),
});
