// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnTimeoutSpec } from "./ReturnTimeoutSpec.mjs";
export const ReturnTimeoutSpecs = core.serialization.object({
    inactivity: ReturnTimeoutSpec,
    maxDuration: core.serialization.property("max_duration", ReturnTimeoutSpec),
});
