// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { AssistantEnd } from "./AssistantEnd.mjs";
import { AssistantMessage } from "./AssistantMessage.mjs";
import { AssistantProsody } from "./AssistantProsody.mjs";
import { AudioOutput } from "./AudioOutput.mjs";
import { ChatMetadata } from "./ChatMetadata.mjs";
import { ToolCallMessage } from "./ToolCallMessage.mjs";
import { ToolErrorMessage } from "./ToolErrorMessage.mjs";
import { ToolResponseMessage } from "./ToolResponseMessage.mjs";
import { UserInterruption } from "./UserInterruption.mjs";
import { UserMessage } from "./UserMessage.mjs";
import { WebSocketError } from "./WebSocketError.mjs";
export const SubscribeEvent = core.serialization.undiscriminatedUnion([
    AssistantEnd,
    AssistantMessage,
    AssistantProsody,
    AudioOutput,
    ChatMetadata,
    WebSocketError,
    UserInterruption,
    UserMessage,
    ToolCallMessage,
    ToolResponseMessage,
    ToolErrorMessage,
]);
