// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ToolType } from "./ToolType.mjs";
export const Tool = core.serialization.object({
    description: core.serialization.string().optional(),
    fallbackContent: core.serialization.property("fallback_content", core.serialization.string().optional()),
    name: core.serialization.string(),
    parameters: core.serialization.string(),
    type: ToolType,
});
