// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ErrorLevel } from "./ErrorLevel.mjs";
import { ToolType } from "./ToolType.mjs";
export const ToolErrorMessage = core.serialization.object({
    code: core.serialization.string().optional(),
    content: core.serialization.string().optional(),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    error: core.serialization.string(),
    level: ErrorLevel.optional(),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
    toolType: core.serialization.property("tool_type", ToolType.optional()),
    type: core.serialization.stringLiteral("tool_error"),
});
