// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ToolType } from "./ToolType.mjs";
export const ToolResponseMessage = core.serialization.object({
    content: core.serialization.string(),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
    toolName: core.serialization.property("tool_name", core.serialization.string().optional()),
    toolType: core.serialization.property("tool_type", ToolType.optional()),
    type: core.serialization.stringLiteral("tool_response"),
});
