// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ToolType } from "./ToolType.mjs";
export const ToolCallMessage = core.serialization.object({
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    name: core.serialization.string(),
    parameters: core.serialization.string(),
    responseRequired: core.serialization.property("response_required", core.serialization.boolean()),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
    toolType: core.serialization.property("tool_type", ToolType),
    type: core.serialization.stringLiteral("tool_call"),
});
