// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const UserInterruption = core.serialization.object({
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    time: core.serialization.number(),
    type: core.serialization.stringLiteral("user_interruption"),
});
