// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ChatMessage } from "./ChatMessage.mjs";
import { Inference } from "./Inference.mjs";
import { MillisecondInterval } from "./MillisecondInterval.mjs";
export const UserMessage = core.serialization.object({
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    fromText: core.serialization.property("from_text", core.serialization.boolean()),
    interim: core.serialization.boolean(),
    language: core.serialization.string().optional(),
    message: ChatMessage,
    models: Inference,
    time: MillisecondInterval,
    type: core.serialization.stringLiteral("user_message"),
});
