// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { VoiceId } from "./VoiceId.mjs";
import { VoiceName } from "./VoiceName.mjs";
export const VoiceRef = core.serialization.undiscriminatedUnion([VoiceId, VoiceName]);
