// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ToolCallMessage } from "./ToolCallMessage.mjs";
import { WebhookEventBase } from "./WebhookEventBase.mjs";
export const WebhookEventToolCall = core.serialization
    .object({
    callerNumber: core.serialization.property("caller_number", core.serialization.string().optional()),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    eventName: core.serialization.property("event_name", core.serialization.stringLiteral("tool_call").optional()),
    timestamp: core.serialization.number(),
    toolCallMessage: core.serialization.property("tool_call_message", ToolCallMessage),
})
    .extend(WebhookEventBase);
