// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { WebhookEventChatEnded } from "./WebhookEventChatEnded.mjs";
import { WebhookEventChatStarted } from "./WebhookEventChatStarted.mjs";
import { WebhookEventToolCall } from "./WebhookEventToolCall.mjs";
export const WebhookEvent = core.serialization.undiscriminatedUnion([WebhookEventChatStarted, WebhookEventChatEnded, WebhookEventToolCall]);
