// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const WebhookEventChatStartType = core.serialization.enum_(["new_chat_group", "resumed_chat_group"]);
