// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const WebSocketError = core.serialization.object({
    code: core.serialization.string(),
    customSessionId: core.serialization.property("custom_session_id", core.serialization.string().optional()),
    message: core.serialization.string(),
    requestId: core.serialization.property("request_id", core.serialization.string().optional()),
    slug: core.serialization.string(),
    type: core.serialization.stringLiteral("error"),
});
