export declare const Bcp47Tag: {
    readonly Zh: "zh";
    readonly Da: "da";
    readonly Nl: "nl";
    readonly En: "en";
    readonly EnAu: "en-AU";
    readonly EnIn: "en-IN";
    readonly EnNz: "en-NZ";
    readonly EnGb: "en-GB";
    readonly Fr: "fr";
    readonly FrCa: "fr-CA";
    readonly De: "de";
    readonly Hi: "hi";
    readonly HiLatn: "hi-Latn";
    readonly Id: "id";
    readonly It: "it";
    readonly Ja: "ja";
    readonly Ko: "ko";
    readonly No: "no";
    readonly Pl: "pl";
    readonly Pt: "pt";
    readonly PtBr: "pt-BR";
    readonly PtPt: "pt-PT";
    readonly Ru: "ru";
    readonly Es: "es";
    readonly Es419: "es-419";
    readonly Sv: "sv";
    readonly Ta: "ta";
    readonly Tr: "tr";
    readonly Uk: "uk";
};
export type Bcp47Tag = (typeof Bcp47Tag)[keyof typeof Bcp47Tag];
