// This file was auto-generated by Fern from our API Definition.
import { EmpathicVoice } from "./api/resources/empathicVoice/client/Client.mjs";
import { ExpressionMeasurement } from "./api/resources/expressionMeasurement/client/Client.mjs";
import { Tts } from "./api/resources/tts/client/Client.mjs";
import { mergeHeaders } from "./core/headers.mjs";
import * as core from "./core/index.mjs";
export class HumeClient {
    constructor(_options = {}) {
        this._options = Object.assign(Object.assign({}, _options), { logging: core.logging.createLogger(_options === null || _options === void 0 ? void 0 : _options.logging), headers: mergeHeaders({
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "hume",
                "X-Fern-SDK-Version": "0.15.6",
                "User-Agent": "hume/0.15.6",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            }, _options === null || _options === void 0 ? void 0 : _options.headers) });
    }
    get tts() {
        var _a;
        return ((_a = this._tts) !== null && _a !== void 0 ? _a : (this._tts = new Tts(this._options)));
    }
    get empathicVoice() {
        var _a;
        return ((_a = this._empathicVoice) !== null && _a !== void 0 ? _a : (this._empathicVoice = new EmpathicVoice(this._options)));
    }
    get expressionMeasurement() {
        var _a;
        return ((_a = this._expressionMeasurement) !== null && _a !== void 0 ? _a : (this._expressionMeasurement = new ExpressionMeasurement(this._options)));
    }
}
