// This file was auto-generated by Fern from our API Definition.
export const HumeEnvironment = {
    Prod: {
        base: "https://api.hume.ai",
        evi: "wss://api.hume.ai/v0/evi",
        tts: "wss://api.hume.ai/v0/tts",
        stream: "wss://api.hume.ai/v0/stream",
    },
};
