// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../core/index.mjs";
import { TtsOutput } from "../../../../types/TtsOutput.mjs";
export const StreamInputSocketResponse = core.serialization.undiscriminatedUnion([TtsOutput]);
