// This file was auto-generated by Fern from our API Definition.
import { Chat } from "../resources/chat/client/Client.mjs";
import { ChatGroups } from "../resources/chatGroups/client/Client.mjs";
import { Chats } from "../resources/chats/client/Client.mjs";
import { Configs } from "../resources/configs/client/Client.mjs";
import { ControlPlane } from "../resources/controlPlane/client/Client.mjs";
import { Prompts } from "../resources/prompts/client/Client.mjs";
import { Tools } from "../resources/tools/client/Client.mjs";
export class EmpathicVoice {
    constructor(_options = {}) {
        this._options = _options;
    }
    get controlPlane() {
        var _a;
        return ((_a = this._controlPlane) !== null && _a !== void 0 ? _a : (this._controlPlane = new ControlPlane(this._options)));
    }
    get chatGroups() {
        var _a;
        return ((_a = this._chatGroups) !== null && _a !== void 0 ? _a : (this._chatGroups = new ChatGroups(this._options)));
    }
    get chats() {
        var _a;
        return ((_a = this._chats) !== null && _a !== void 0 ? _a : (this._chats = new Chats(this._options)));
    }
    get configs() {
        var _a;
        return ((_a = this._configs) !== null && _a !== void 0 ? _a : (this._configs = new Configs(this._options)));
    }
    get prompts() {
        var _a;
        return ((_a = this._prompts) !== null && _a !== void 0 ? _a : (this._prompts = new Prompts(this._options)));
    }
    get tools() {
        var _a;
        return ((_a = this._tools) !== null && _a !== void 0 ? _a : (this._tools = new Tools(this._options)));
    }
    get chat() {
        var _a;
        return ((_a = this._chat) !== null && _a !== void 0 ? _a : (this._chat = new Chat(this._options)));
    }
}
