"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnionPredictResult = void 0;
const InferenceSourcePredictResult_js_1 = require("./InferenceSourcePredictResult.js");
exports.UnionPredictResult = InferenceSourcePredictResult_js_1.InferenceSourcePredictResult;
