"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnionJob = void 0;
const InferenceJob_js_1 = require("./InferenceJob.js");
exports.UnionJob = InferenceJob_js_1.InferenceJob;
