"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostedPromptVersionDescription = exports.PostedPromptVersion = exports.PostedPromptName = exports.PostedPrompt = void 0;
var PostedPrompt_js_1 = require("./PostedPrompt.js");
Object.defineProperty(exports, "PostedPrompt", { enumerable: true, get: function () { return PostedPrompt_js_1.PostedPrompt; } });
var PostedPromptName_js_1 = require("./PostedPromptName.js");
Object.defineProperty(exports, "PostedPromptName", { enumerable: true, get: function () { return PostedPromptName_js_1.PostedPromptName; } });
var PostedPromptVersion_js_1 = require("./PostedPromptVersion.js");
Object.defineProperty(exports, "PostedPromptVersion", { enumerable: true, get: function () { return PostedPromptVersion_js_1.PostedPromptVersion; } });
var PostedPromptVersionDescription_js_1 = require("./PostedPromptVersionDescription.js");
Object.defineProperty(exports, "PostedPromptVersionDescription", { enumerable: true, get: function () { return PostedPromptVersionDescription_js_1.PostedPromptVersionDescription; } });
