"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelProviderEnum = void 0;
exports.ModelProviderEnum = {
    Groq: "GROQ",
    OpenAi: "OPEN_AI",
    Fireworks: "FIREWORKS",
    Anthropic: "ANTHROPIC",
    CustomLanguageModel: "CUSTOM_LANGUAGE_MODEL",
    Google: "GOOGLE",
    HumeAi: "HUME_AI",
    AmazonBedrock: "AMAZON_BEDROCK",
    Perplexity: "PERPLEXITY",
    Sambanova: "SAMBANOVA",
    Cerebras: "CEREBRAS",
};
