"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReturnBuiltinToolToolType = void 0;
/** Type of Tool. Either `BUILTIN` for natively implemented tools, like web search, or `FUNCTION` for user-defined tools. */
exports.ReturnBuiltinToolToolType = {
    Builtin: "BUILTIN",
    Function: "FUNCTION",
};
