"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReturnUserDefinedToolVersionType = void 0;
/** Versioning method for a Tool. Either `FIXED` for using a fixed version number or `LATEST` for auto-updating to the latest version. */
exports.ReturnUserDefinedToolVersionType = {
    Fixed: "FIXED",
    Latest: "LATEST",
};
