"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReturnChatPagedEventsStatus = void 0;
/**
 * Indicates the current state of the chat. There are six possible statuses:
 *
 * - `ACTIVE`: The chat is currently active and ongoing.
 *
 * - `USER_ENDED`: The chat was manually ended by the user.
 *
 * - `USER_TIMEOUT`: The chat ended due to a user-defined timeout.
 *
 * - `MAX_DURATION_TIMEOUT`: The chat ended because it reached the maximum allowed duration.
 *
 * - `INACTIVITY_TIMEOUT`: The chat ended due to an inactivity timeout.
 *
 * - `ERROR`: The chat ended unexpectedly due to an error.
 */
exports.ReturnChatPagedEventsStatus = {
    Active: "ACTIVE",
    UserEnded: "USER_ENDED",
    UserTimeout: "USER_TIMEOUT",
    MaxDurationTimeout: "MAX_DURATION_TIMEOUT",
    InactivityTimeout: "INACTIVITY_TIMEOUT",
    Error: "ERROR",
};
