"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReturnWebhookEventType = void 0;
/** Events this URL is subscribed to */
exports.ReturnWebhookEventType = {
    ChatStarted: "chat_started",
    ChatEnded: "chat_ended",
    ToolCall: "tool_call",
};
