"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubscribeEvent = void 0;
const core = __importStar(require("../../../../core/index.js"));
const AssistantEnd_js_1 = require("./AssistantEnd.js");
const AssistantMessage_js_1 = require("./AssistantMessage.js");
const AssistantProsody_js_1 = require("./AssistantProsody.js");
const AudioOutput_js_1 = require("./AudioOutput.js");
const ChatMetadata_js_1 = require("./ChatMetadata.js");
const ToolCallMessage_js_1 = require("./ToolCallMessage.js");
const ToolErrorMessage_js_1 = require("./ToolErrorMessage.js");
const ToolResponseMessage_js_1 = require("./ToolResponseMessage.js");
const UserInterruption_js_1 = require("./UserInterruption.js");
const UserMessage_js_1 = require("./UserMessage.js");
const WebSocketError_js_1 = require("./WebSocketError.js");
exports.SubscribeEvent = core.serialization.undiscriminatedUnion([
    AssistantEnd_js_1.AssistantEnd,
    AssistantMessage_js_1.AssistantMessage,
    AssistantProsody_js_1.AssistantProsody,
    AudioOutput_js_1.AudioOutput,
    ChatMetadata_js_1.ChatMetadata,
    WebSocketError_js_1.WebSocketError,
    UserInterruption_js_1.UserInterruption,
    UserMessage_js_1.UserMessage,
    ToolCallMessage_js_1.ToolCallMessage,
    ToolResponseMessage_js_1.ToolResponseMessage,
    ToolErrorMessage_js_1.ToolErrorMessage,
]);
