// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { DescriptionsScore } from "./DescriptionsScore.mjs";
import { EmotionScore } from "./EmotionScore.mjs";
import { TimeInterval } from "./TimeInterval.mjs";
export const BurstPrediction = core.serialization.object({
    time: TimeInterval,
    emotions: core.serialization.list(EmotionScore),
    descriptions: core.serialization.list(DescriptionsScore),
});
