// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { CompletedInference } from "./CompletedInference.mjs";
export const CompletedState = core.serialization.object({}).extend(CompletedInference);
