// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { JobTlInference } from "./JobTlInference.mjs";
export const CustomModelsInferenceJob = core.serialization
    .object({
    type: core.serialization.string(),
})
    .extend(JobTlInference);
