// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { CustomModelId } from "./CustomModelId.mjs";
import { CustomModelVersionId } from "./CustomModelVersionId.mjs";
export const CustomModel = core.serialization.undiscriminatedUnion([CustomModelId, CustomModelVersionId]);
