// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { JobTraining } from "./JobTraining.mjs";
export const CustomModelsTrainingJob = core.serialization
    .object({
    type: core.serialization.string(),
})
    .extend(JobTraining);
