// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
export const DatasetId = core.serialization.object({
    id: core.serialization.string(),
});
