// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { JobEmbeddingGeneration } from "./JobEmbeddingGeneration.mjs";
export const EmbeddingGenerationJob = core.serialization
    .object({
    type: core.serialization.string(),
})
    .extend(JobEmbeddingGeneration);
