// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { ValidationArgs } from "./ValidationArgs.mjs";
export const EvaluationArgs = core.serialization.object({
    validation: ValidationArgs.optional(),
});
