// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { BoundingBox } from "./BoundingBox.mjs";
import { DescriptionsScore } from "./DescriptionsScore.mjs";
import { EmotionScore } from "./EmotionScore.mjs";
import { FacsScore } from "./FacsScore.mjs";
export const FacePrediction = core.serialization.object({
    frame: core.serialization.number(),
    time: core.serialization.number(),
    prob: core.serialization.number(),
    box: BoundingBox,
    emotions: core.serialization.list(EmotionScore),
    facs: core.serialization.list(FacsScore).optional(),
    descriptions: core.serialization.list(DescriptionsScore).optional(),
});
