// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { EmotionScore } from "./EmotionScore.mjs";
export const FacemeshPrediction = core.serialization.object({
    emotions: core.serialization.list(EmotionScore),
});
