// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { FacePrediction } from "./FacePrediction.mjs";
export const GroupedPredictionsFacePrediction = core.serialization.object({
    id: core.serialization.string(),
    predictions: core.serialization.list(FacePrediction),
});
