// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { FacemeshPrediction } from "./FacemeshPrediction.mjs";
export const GroupedPredictionsFacemeshPrediction = core.serialization.object({
    id: core.serialization.string(),
    predictions: core.serialization.list(FacemeshPrediction),
});
