// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { NerPrediction } from "./NerPrediction.mjs";
export const GroupedPredictionsNerPrediction = core.serialization.object({
    id: core.serialization.string(),
    predictions: core.serialization.list(NerPrediction),
});
