// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { ProsodyPrediction } from "./ProsodyPrediction.mjs";
export const GroupedPredictionsProsodyPrediction = core.serialization.object({
    id: core.serialization.string(),
    predictions: core.serialization.list(ProsodyPrediction),
});
