// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { LanguagePrediction } from "./LanguagePrediction.mjs";
export const GroupedPredictionsLanguagePrediction = core.serialization.object({
    id: core.serialization.string(),
    predictions: core.serialization.list(LanguagePrediction),
});
