// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { BurstPrediction } from "./BurstPrediction.mjs";
export const GroupedPredictionsBurstPrediction = core.serialization.object({
    id: core.serialization.string(),
    predictions: core.serialization.list(BurstPrediction),
});
