// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Error_ } from "./Error_.mjs";
import { InferencePrediction } from "./InferencePrediction.mjs";
export const InferenceResults = core.serialization.object({
    predictions: core.serialization.list(InferencePrediction),
    errors: core.serialization.list(Error_),
});
