// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { ModelsPredictions } from "./ModelsPredictions.mjs";
export const InferencePrediction = core.serialization.object({
    file: core.serialization.string(),
    models: ModelsPredictions,
});
