// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { InferenceResults } from "./InferenceResults.mjs";
import { Source } from "./Source.mjs";
export const InferenceSourcePredictResult = core.serialization.object({
    source: Source,
    results: InferenceResults.optional(),
    error: core.serialization.string().optional(),
});
