// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { EmbeddingGenerationBaseRequest } from "./EmbeddingGenerationBaseRequest.mjs";
import { StateEmbeddingGeneration } from "./StateEmbeddingGeneration.mjs";
export const JobEmbeddingGeneration = core.serialization.object({
    jobId: core.serialization.property("job_id", core.serialization.string()),
    userId: core.serialization.property("user_id", core.serialization.string()),
    request: EmbeddingGenerationBaseRequest,
    state: StateEmbeddingGeneration,
});
