// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { InferenceRequest } from "./InferenceRequest.mjs";
import { StateInference } from "./StateInference.mjs";
export const JobInference = core.serialization.object({
    jobId: core.serialization.property("job_id", core.serialization.string()),
    request: InferenceRequest,
    state: StateInference,
});
