// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { StateTraining } from "./StateTraining.mjs";
import { TrainingBaseRequest } from "./TrainingBaseRequest.mjs";
export const JobTraining = core.serialization.object({
    jobId: core.serialization.property("job_id", core.serialization.string()),
    userId: core.serialization.property("user_id", core.serialization.string()),
    request: TrainingBaseRequest,
    state: StateTraining,
});
