// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { StateTlInference } from "./StateTlInference.mjs";
import { TlInferenceBaseRequest } from "./TlInferenceBaseRequest.mjs";
export const JobTlInference = core.serialization.object({
    jobId: core.serialization.property("job_id", core.serialization.string()),
    userId: core.serialization.property("user_id", core.serialization.string()),
    request: TlInferenceBaseRequest,
    state: StateTlInference,
});
