// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { EmotionScore } from "./EmotionScore.mjs";
import { PositionInterval } from "./PositionInterval.mjs";
import { SentimentScore } from "./SentimentScore.mjs";
import { TimeInterval } from "./TimeInterval.mjs";
import { ToxicityScore } from "./ToxicityScore.mjs";
export const LanguagePrediction = core.serialization.object({
    text: core.serialization.string(),
    position: PositionInterval,
    time: TimeInterval.optional(),
    confidence: core.serialization.number().optional(),
    speakerConfidence: core.serialization.property("speaker_confidence", core.serialization.number().optional()),
    emotions: core.serialization.list(EmotionScore),
    sentiment: core.serialization.list(SentimentScore).optional(),
    toxicity: core.serialization.list(ToxicityScore).optional(),
});
