// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Granularity } from "./Granularity.mjs";
import { Unconfigurable } from "./Unconfigurable.mjs";
export const Language = core.serialization.object({
    granularity: Granularity.optional(),
    sentiment: Unconfigurable.optional(),
    toxicity: Unconfigurable.optional(),
    identifySpeakers: core.serialization.property("identify_speakers", core.serialization.boolean().optional()),
});
