// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Face } from "./Face.mjs";
import { Language } from "./Language.mjs";
import { Ner } from "./Ner.mjs";
import { Prosody } from "./Prosody.mjs";
import { Unconfigurable } from "./Unconfigurable.mjs";
export const Models = core.serialization.object({
    face: Face.optional(),
    burst: Unconfigurable.optional(),
    prosody: Prosody.optional(),
    language: Language.optional(),
    ner: Ner.optional(),
    facemesh: Unconfigurable.optional(),
});
