// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
export const Ner = core.serialization.object({
    identifySpeakers: core.serialization.property("identify_speakers", core.serialization.boolean().optional()),
});
