// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { EmotionScore } from "./EmotionScore.mjs";
import { PositionInterval } from "./PositionInterval.mjs";
import { TimeInterval } from "./TimeInterval.mjs";
export const NerPrediction = core.serialization.object({
    entity: core.serialization.string(),
    position: PositionInterval,
    entityConfidence: core.serialization.property("entity_confidence", core.serialization.number()),
    support: core.serialization.number(),
    uri: core.serialization.string(),
    linkWord: core.serialization.property("link_word", core.serialization.string()),
    time: TimeInterval.optional(),
    confidence: core.serialization.number().optional(),
    speakerConfidence: core.serialization.property("speaker_confidence", core.serialization.number().optional()),
    emotions: core.serialization.list(EmotionScore),
});
