// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { GroupedPredictionsFacePrediction } from "./GroupedPredictionsFacePrediction.mjs";
import { Null } from "./Null.mjs";
export const PredictionsOptionalNullFacePrediction = core.serialization.object({
    metadata: Null.optional(),
    groupedPredictions: core.serialization.property("grouped_predictions", core.serialization.list(GroupedPredictionsFacePrediction)),
});
