// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { GroupedPredictionsNerPrediction } from "./GroupedPredictionsNerPrediction.mjs";
import { TranscriptionMetadata } from "./TranscriptionMetadata.mjs";
export const PredictionsOptionalTranscriptionMetadataNerPrediction = core.serialization.object({
    metadata: TranscriptionMetadata.optional(),
    groupedPredictions: core.serialization.property("grouped_predictions", core.serialization.list(GroupedPredictionsNerPrediction)),
});
