// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { EmotionScore } from "./EmotionScore.mjs";
import { TimeInterval } from "./TimeInterval.mjs";
export const ProsodyPrediction = core.serialization.object({
    text: core.serialization.string().optional(),
    time: TimeInterval,
    confidence: core.serialization.number().optional(),
    speakerConfidence: core.serialization.property("speaker_confidence", core.serialization.number().optional()),
    emotions: core.serialization.list(EmotionScore),
});
