// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { File_ } from "./File_.mjs";
export const SourceFile = core.serialization.object({}).extend(File_);
