// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { SourceFile } from "./SourceFile.mjs";
import { SourceTextSource } from "./SourceTextSource.mjs";
import { SourceUrl } from "./SourceUrl.mjs";
export const Source = core.serialization
    .union("type", {
    url: SourceUrl,
    file: SourceFile,
    text: SourceTextSource,
})
    .transform({
    transform: (value) => value,
    untransform: (value) => value,
});
