// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { CompletedTraining } from "./CompletedTraining.mjs";
export const StateTrainingCompletedTraining = core.serialization.object({}).extend(CompletedTraining);
