// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { CompletedEmbeddingGeneration } from "./CompletedEmbeddingGeneration.mjs";
export const StateEmbeddingGenerationCompletedEmbeddingGeneration = core.serialization.object({}).extend(CompletedEmbeddingGeneration);
