// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { CompletedState } from "./CompletedState.mjs";
import { FailedState } from "./FailedState.mjs";
import { InProgressState } from "./InProgressState.mjs";
import { QueuedState } from "./QueuedState.mjs";
export const StateInference = core.serialization
    .union("status", {
    QUEUED: QueuedState,
    IN_PROGRESS: InProgressState,
    COMPLETED: CompletedState,
    FAILED: FailedState,
})
    .transform({
    transform: (value) => value,
    untransform: (value) => value,
});
