// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { StateEmbeddingGenerationCompletedEmbeddingGeneration } from "./StateEmbeddingGenerationCompletedEmbeddingGeneration.mjs";
import { StateEmbeddingGenerationFailed } from "./StateEmbeddingGenerationFailed.mjs";
import { StateEmbeddingGenerationInProgress } from "./StateEmbeddingGenerationInProgress.mjs";
import { StateEmbeddingGenerationQueued } from "./StateEmbeddingGenerationQueued.mjs";
export const StateEmbeddingGeneration = core.serialization
    .union("status", {
    QUEUED: StateEmbeddingGenerationQueued,
    IN_PROGRESS: StateEmbeddingGenerationInProgress,
    COMPLETED: StateEmbeddingGenerationCompletedEmbeddingGeneration,
    FAILED: StateEmbeddingGenerationFailed,
})
    .transform({
    transform: (value) => value,
    untransform: (value) => value,
});
