// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { StateTlInferenceCompletedTlInference } from "./StateTlInferenceCompletedTlInference.mjs";
import { StateTlInferenceFailed } from "./StateTlInferenceFailed.mjs";
import { StateTlInferenceInProgress } from "./StateTlInferenceInProgress.mjs";
import { StateTlInferenceQueued } from "./StateTlInferenceQueued.mjs";
export const StateTlInference = core.serialization
    .union("status", {
    QUEUED: StateTlInferenceQueued,
    IN_PROGRESS: StateTlInferenceInProgress,
    COMPLETED: StateTlInferenceCompletedTlInference,
    FAILED: StateTlInferenceFailed,
})
    .transform({
    transform: (value) => value,
    untransform: (value) => value,
});
