// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Queued } from "./Queued.mjs";
export const StateTrainingQueued = core.serialization.object({}).extend(Queued);
