// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { InProgress } from "./InProgress.mjs";
export const StateTlInferenceInProgress = core.serialization.object({}).extend(InProgress);
