// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Failed } from "./Failed.mjs";
export const StateEmbeddingGenerationFailed = core.serialization.object({}).extend(Failed);
