// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { StateTrainingCompletedTraining } from "./StateTrainingCompletedTraining.mjs";
import { StateTrainingFailed } from "./StateTrainingFailed.mjs";
import { StateTrainingInProgress } from "./StateTrainingInProgress.mjs";
import { StateTrainingQueued } from "./StateTrainingQueued.mjs";
export const StateTraining = core.serialization
    .union("status", {
    QUEUED: StateTrainingQueued,
    IN_PROGRESS: StateTrainingInProgress,
    COMPLETED: StateTrainingCompletedTraining,
    FAILED: StateTrainingFailed,
})
    .transform({
    transform: (value) => value,
    untransform: (value) => value,
});
