// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
export const Tag = core.serialization.object({
    key: core.serialization.string(),
    value: core.serialization.string(),
});
