// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { CustomModel } from "./CustomModel.mjs";
export const TlInferenceBaseRequest = core.serialization.object({
    customModel: core.serialization.property("custom_model", CustomModel),
    urls: core.serialization.list(core.serialization.string()).optional(),
    callbackUrl: core.serialization.property("callback_url", core.serialization.string().optional()),
    notify: core.serialization.boolean().optional(),
});
