// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Error_ } from "./Error_.mjs";
import { TlInferencePrediction } from "./TlInferencePrediction.mjs";
export const TlInferenceResults = core.serialization.object({
    predictions: core.serialization.list(TlInferencePrediction),
    errors: core.serialization.list(Error_),
});
