// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Source } from "./Source.mjs";
import { TlInferenceResults } from "./TlInferenceResults.mjs";
export const TlInferenceSourcePredictResult = core.serialization.object({
    source: Source,
    results: TlInferenceResults.optional(),
    error: core.serialization.string().optional(),
});
