// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { CustomModelPrediction } from "./CustomModelPrediction.mjs";
export const TlInferencePrediction = core.serialization.object({
    file: core.serialization.string(),
    fileType: core.serialization.property("file_type", core.serialization.string()),
    customModels: core.serialization.property("custom_models", core.serialization.record(core.serialization.string(), CustomModelPrediction)),
});
