// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Alternative } from "./Alternative.mjs";
import { CustomModelRequest } from "./CustomModelRequest.mjs";
import { Dataset } from "./Dataset.mjs";
import { EvaluationArgs } from "./EvaluationArgs.mjs";
import { Task } from "./Task.mjs";
export const TrainingBaseRequest = core.serialization.object({
    customModel: core.serialization.property("custom_model", CustomModelRequest),
    dataset: Dataset,
    targetFeature: core.serialization.property("target_feature", core.serialization.string().optional()),
    task: Task.optional(),
    evaluation: EvaluationArgs.optional(),
    alternatives: core.serialization.list(Alternative).optional(),
    callbackUrl: core.serialization.property("callback_url", core.serialization.string().optional()),
    notify: core.serialization.boolean().optional(),
});
