// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { Bcp47Tag } from "./Bcp47Tag.mjs";
export const TranscriptionMetadata = core.serialization.object({
    confidence: core.serialization.number(),
    detectedLanguage: core.serialization.property("detected_language", Bcp47Tag.optional()),
});
