// This file was auto-generated by Fern from our API Definition.
import { InferenceSourcePredictResult } from "./InferenceSourcePredictResult.mjs";
export const UnionPredictResult = InferenceSourcePredictResult;
