"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SnippetAudioChunk = void 0;
const core = __importStar(require("../../../../core/index.js"));
const AudioFormatType_js_1 = require("./AudioFormatType.js");
const Snippet_js_1 = require("./Snippet.js");
exports.SnippetAudioChunk = core.serialization.object({
    audio: core.serialization.string(),
    audioFormat: core.serialization.property("audio_format", AudioFormatType_js_1.AudioFormatType),
    chunkIndex: core.serialization.property("chunk_index", core.serialization.number()),
    generationId: core.serialization.property("generation_id", core.serialization.string()),
    isLastChunk: core.serialization.property("is_last_chunk", core.serialization.boolean()),
    requestId: core.serialization.property("request_id", core.serialization.string()),
    snippet: Snippet_js_1.Snippet.optional(),
    snippetId: core.serialization.property("snippet_id", core.serialization.string()),
    text: core.serialization.string(),
    transcribedText: core.serialization.property("transcribed_text", core.serialization.string().optional()),
    type: core.serialization.stringLiteral("audio"),
    utteranceIndex: core.serialization.property("utterance_index", core.serialization.number().optional()),
});
