// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../core/index.mjs";
import { AssistantInput } from "../../../types/AssistantInput.mjs";
import { AudioInput } from "../../../types/AudioInput.mjs";
import { PauseAssistantMessage } from "../../../types/PauseAssistantMessage.mjs";
import { ResumeAssistantMessage } from "../../../types/ResumeAssistantMessage.mjs";
import { SessionSettings } from "../../../types/SessionSettings.mjs";
import { ToolErrorMessage } from "../../../types/ToolErrorMessage.mjs";
import { ToolResponseMessage } from "../../../types/ToolResponseMessage.mjs";
import { UserInput } from "../../../types/UserInput.mjs";
export const PublishEvent = core.serialization.undiscriminatedUnion([
    AudioInput,
    SessionSettings,
    UserInput,
    AssistantInput,
    ToolResponseMessage,
    ToolErrorMessage,
    PauseAssistantMessage,
    ResumeAssistantMessage,
]);
