// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
export const JobDetails = core.serialization.object({
    jobId: core.serialization.property("job_id", core.serialization.string().optional()),
});
