// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
import { EmotionEmbedding } from "../../../types/EmotionEmbedding.mjs";
export const StreamModelPredictionsFacemeshPredictionsItem = core.serialization.object({
    emotions: EmotionEmbedding.optional(),
});
