// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
import { EmotionEmbedding } from "../../../types/EmotionEmbedding.mjs";
import { Sentiment } from "../../../types/Sentiment.mjs";
import { TextPosition } from "../../../types/TextPosition.mjs";
import { Toxicity } from "../../../types/Toxicity.mjs";
export const StreamModelPredictionsLanguagePredictionsItem = core.serialization.object({
    text: core.serialization.string().optional(),
    position: TextPosition.optional(),
    emotions: EmotionEmbedding.optional(),
    sentiment: Sentiment.optional(),
    toxicity: Toxicity.optional(),
});
