// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
import { EmotionEmbedding } from "../../../types/EmotionEmbedding.mjs";
import { TimeRange } from "../../../types/TimeRange.mjs";
export const StreamModelPredictionsProsodyPredictionsItem = core.serialization.object({
    time: TimeRange.optional(),
    emotions: EmotionEmbedding.optional(),
});
