// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
import { StreamModelPredictionsBurstPredictionsItem } from "./StreamModelPredictionsBurstPredictionsItem.mjs";
export const StreamModelPredictionsBurst = core.serialization.object({
    predictions: core.serialization.list(StreamModelPredictionsBurstPredictionsItem).optional(),
});
