// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
import { StreamModelPredictionsFacemeshPredictionsItem } from "./StreamModelPredictionsFacemeshPredictionsItem.mjs";
export const StreamModelPredictionsFacemesh = core.serialization.object({
    predictions: core.serialization.list(StreamModelPredictionsFacemeshPredictionsItem).optional(),
});
