// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
import { StreamModelPredictionsFacePredictionsItem } from "./StreamModelPredictionsFacePredictionsItem.mjs";
export const StreamModelPredictionsFace = core.serialization.object({
    predictions: core.serialization.list(StreamModelPredictionsFacePredictionsItem).optional(),
});
