// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
import { StreamModelPredictionsLanguagePredictionsItem } from "./StreamModelPredictionsLanguagePredictionsItem.mjs";
export const StreamModelPredictionsLanguage = core.serialization.object({
    predictions: core.serialization.list(StreamModelPredictionsLanguagePredictionsItem).optional(),
});
