// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../../core/index.mjs";
import { StreamErrorMessage } from "./StreamErrorMessage.mjs";
import { StreamModelPredictions } from "./StreamModelPredictions.mjs";
import { StreamWarningMessage } from "./StreamWarningMessage.mjs";
export const SubscribeEvent = core.serialization.undiscriminatedUnion([StreamModelPredictions, StreamErrorMessage, StreamWarningMessage]);
