export const KNOBS_CONFIG = {
  // AGC (Automatic Gain Control)
  "agc.enabled": {
    id: "agc.enabled",
    name: "AGC Enabled",
    category: "agc",
    type: "boolean" as const,
    description: "Enable or disable automatic gain control on the input",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "agc.target_level_dbfs": {
    id: "agc.target_level_dbfs",
    name: "AGC Target Level",
    category: "agc",
    type: "numeric" as const,
    description: "Target RMS level relative to full scale for AGC",
    unit: "dBFS",
    validRange: { min: -60, max: 0 },
    recommendedRange: { min: -24, max: -14 },
    aiAdjustmentRange: { min: -30, max: -10 },
    optimum: -18,
    currentValue: -18,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "agc.compression_ratio": {
    id: "agc.compression_ratio",
    name: "AGC Compression Ratio",
    category: "agc",
    type: "numeric" as const,
    description: "Gain compression ratio used by AGC",
    unit: "ratio",
    validRange: { min: 1.0, max: 10.0 },
    recommendedRange: { min: 2.0, max: 6.0 },
    aiAdjustmentRange: { min: 1.5, max: 8.0 },
    optimum: 4.0,
    currentValue: 3.5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "agc.attack_time_ms": {
    id: "agc.attack_time_ms",
    name: "AGC Attack Time",
    category: "agc",
    type: "numeric" as const,
    description: "Attack time of AGC envelope follower",
    unit: "ms",
    validRange: { min: 1, max: 100 },
    recommendedRange: { min: 5, max: 20 },
    aiAdjustmentRange: { min: 1, max: 50 },
    optimum: 10,
    currentValue: 12,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "agc.release_time_ms": {
    id: "agc.release_time_ms",
    name: "AGC Release Time",
    category: "agc",
    type: "numeric" as const,
    description: "Release time of AGC envelope follower",
    unit: "ms",
    validRange: { min: 20, max: 1000 },
    recommendedRange: { min: 80, max: 400 },
    aiAdjustmentRange: { min: 50, max: 800 },
    optimum: 200,
    currentValue: 180,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "agc.max_gain_db": {
    id: "agc.max_gain_db",
    name: "AGC Max Gain",
    category: "agc",
    type: "numeric" as const,
    description: "Maximum gain AGC is allowed to apply",
    unit: "dB",
    validRange: { min: 0, max: 60 },
    recommendedRange: { min: 10, max: 40 },
    aiAdjustmentRange: { min: 6, max: 50 },
    optimum: 25,
    currentValue: 28,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "agc.min_gain_db": {
    id: "agc.min_gain_db",
    name: "AGC Min Gain",
    category: "agc",
    type: "numeric" as const,
    description: "Minimum gain AGC is allowed to apply",
    unit: "dB",
    validRange: { min: -20, max: 0 },
    recommendedRange: { min: -10, max: 0 },
    aiAdjustmentRange: { min: -15, max: 0 },
    optimum: -3,
    currentValue: -3,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "agc.knee_width_db": {
    id: "agc.knee_width_db",
    name: "AGC Knee Width",
    category: "agc",
    type: "numeric" as const,
    description: "Smooth transition width around compression threshold",
    unit: "dB",
    validRange: { min: 0, max: 20 },
    recommendedRange: { min: 2, max: 10 },
    aiAdjustmentRange: { min: 1, max: 15 },
    optimum: 5,
    currentValue: 5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // AEC (Acoustic Echo Cancellation)
  "aec.enabled": {
    id: "aec.enabled",
    name: "AEC Enabled",
    category: "aec",
    type: "boolean" as const,
    description: "Enable or disable acoustic echo cancellation",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "aec.suppression_level_db": {
    id: "aec.suppression_level_db",
    name: "AEC Suppression Level",
    category: "aec",
    type: "numeric" as const,
    description: "Target echo suppression depth",
    unit: "dB",
    validRange: { min: -60, max: 0 },
    recommendedRange: { min: -45, max: -20 },
    aiAdjustmentRange: { min: -50, max: -10 },
    optimum: -30,
    currentValue: -32,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "aec.tail_length_ms": {
    id: "aec.tail_length_ms",
    name: "AEC Tail Length",
    category: "aec",
    type: "numeric" as const,
    description: "Maximum echo tail length handled by the AEC",
    unit: "ms",
    validRange: { min: 32, max: 1024 },
    recommendedRange: { min: 64, max: 256 },
    aiAdjustmentRange: { min: 64, max: 512 },
    optimum: 128,
    currentValue: 150,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "aec.nlp_mode": {
    id: "aec.nlp_mode",
    name: "AEC NLP Mode",
    category: "aec",
    type: "enum" as const,
    description: "Non-linear processing aggressiveness for echo residual",
    unit: "enum",
    validValues: ["off", "mild", "moderate", "aggressive"],
    recommendedValues: ["moderate"],
    aiAllowedValues: ["mild", "moderate", "aggressive"],
    currentValue: "moderate",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "aec.adaptation_rate": {
    id: "aec.adaptation_rate",
    name: "AEC Adaptation Rate",
    category: "aec",
    type: "numeric" as const,
    description: "Rate at which AEC filter adapts to changes",
    unit: "factor",
    validRange: { min: 0.1, max: 2.0 },
    recommendedRange: { min: 0.5, max: 1.5 },
    aiAdjustmentRange: { min: 0.3, max: 2.0 },
    optimum: 1.0,
    currentValue: 1.0,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "aec.convergence_time_s": {
    id: "aec.convergence_time_s",
    name: "AEC Convergence Time",
    category: "aec",
    type: "numeric" as const,
    description: "Time for AEC to fully converge on echo path",
    unit: "s",
    validRange: { min: 0.5, max: 10.0 },
    recommendedRange: { min: 1.0, max: 5.0 },
    aiAdjustmentRange: { min: 0.5, max: 8.0 },
    optimum: 2.0,
    currentValue: 2.5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "aec.doubletalk_threshold": {
    id: "aec.doubletalk_threshold",
    name: "Doubletalk Threshold",
    category: "aec",
    type: "numeric" as const,
    description: "Threshold for detecting simultaneous local and far-end speech",
    unit: "ratio",
    validRange: { min: 0.1, max: 1.0 },
    recommendedRange: { min: 0.3, max: 0.7 },
    aiAdjustmentRange: { min: 0.2, max: 0.9 },
    optimum: 0.5,
    currentValue: 0.5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Noise Reduction (NR)
  "nr.enabled": {
    id: "nr.enabled",
    name: "NR Enabled",
    category: "nr",
    type: "boolean" as const,
    description: "Enable or disable noise reduction stage",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "nr.suppression_level_db": {
    id: "nr.suppression_level_db",
    name: "NR Suppression Level",
    category: "nr",
    type: "numeric" as const,
    description: "Noise attenuation applied by NR",
    unit: "dB",
    validRange: { min: -30, max: 0 },
    recommendedRange: { min: -18, max: -6 },
    aiAdjustmentRange: { min: -24, max: -3 },
    optimum: -12,
    currentValue: -10,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "nr.spectral_floor_db": {
    id: "nr.spectral_floor_db",
    name: "NR Spectral Floor",
    category: "nr",
    type: "numeric" as const,
    description: "Minimum spectral floor to avoid musical noise",
    unit: "dB",
    validRange: { min: -90, max: -40 },
    recommendedRange: { min: -80, max: -60 },
    aiAdjustmentRange: { min: -85, max: -55 },
    optimum: -70,
    currentValue: -68,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "nr.frequency_smoothing": {
    id: "nr.frequency_smoothing",
    name: "NR Frequency Smoothing",
    category: "nr",
    type: "numeric" as const,
    description: "Amount of smoothing applied across frequency bins",
    unit: "factor",
    validRange: { min: 0.0, max: 1.0 },
    recommendedRange: { min: 0.2, max: 0.6 },
    aiAdjustmentRange: { min: 0.1, max: 0.8 },
    optimum: 0.4,
    currentValue: 0.4,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "nr.time_smoothing": {
    id: "nr.time_smoothing",
    name: "NR Time Smoothing",
    category: "nr",
    type: "numeric" as const,
    description: "Amount of smoothing applied over time",
    unit: "factor",
    validRange: { min: 0.0, max: 1.0 },
    recommendedRange: { min: 0.3, max: 0.7 },
    aiAdjustmentRange: { min: 0.2, max: 0.9 },
    optimum: 0.5,
    currentValue: 0.5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "nr.noise_gate_threshold_db": {
    id: "nr.noise_gate_threshold_db",
    name: "Noise Gate Threshold",
    category: "nr",
    type: "numeric" as const,
    description: "Level below which noise gate closes",
    unit: "dB",
    validRange: { min: -80, max: -20 },
    recommendedRange: { min: -60, max: -40 },
    aiAdjustmentRange: { min: -70, max: -30 },
    optimum: -50,
    currentValue: -48,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Compressor
  "compressor.enabled": {
    id: "compressor.enabled",
    name: "Compressor Enabled",
    category: "compressor",
    type: "boolean" as const,
    description: "Enable or disable dynamic range compressor",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false, true],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "compressor.threshold_dbfs": {
    id: "compressor.threshold_dbfs",
    name: "Compressor Threshold",
    category: "compressor",
    type: "numeric" as const,
    description: "Level at which compression starts",
    unit: "dBFS",
    validRange: { min: -40, max: 0 },
    recommendedRange: { min: -24, max: -6 },
    aiAdjustmentRange: { min: -30, max: -3 },
    optimum: -15,
    currentValue: -15,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "compressor.ratio": {
    id: "compressor.ratio",
    name: "Compressor Ratio",
    category: "compressor",
    type: "numeric" as const,
    description: "Compression ratio once above threshold",
    unit: "ratio",
    validRange: { min: 1.0, max: 20.0 },
    recommendedRange: { min: 2.0, max: 6.0 },
    aiAdjustmentRange: { min: 1.5, max: 10.0 },
    optimum: 4.0,
    currentValue: 3.5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "compressor.attack_time_ms": {
    id: "compressor.attack_time_ms",
    name: "Compressor Attack Time",
    category: "compressor",
    type: "numeric" as const,
    description: "Time for compressor to engage",
    unit: "ms",
    validRange: { min: 0.1, max: 100 },
    recommendedRange: { min: 1, max: 20 },
    aiAdjustmentRange: { min: 0.5, max: 50 },
    optimum: 5,
    currentValue: 5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "compressor.release_time_ms": {
    id: "compressor.release_time_ms",
    name: "Compressor Release Time",
    category: "compressor",
    type: "numeric" as const,
    description: "Time for compressor to release",
    unit: "ms",
    validRange: { min: 10, max: 1000 },
    recommendedRange: { min: 50, max: 300 },
    aiAdjustmentRange: { min: 20, max: 500 },
    optimum: 150,
    currentValue: 150,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "compressor.knee_width_db": {
    id: "compressor.knee_width_db",
    name: "Compressor Knee Width",
    category: "compressor",
    type: "numeric" as const,
    description: "Width of soft-knee transition",
    unit: "dB",
    validRange: { min: 0, max: 20 },
    recommendedRange: { min: 2, max: 10 },
    aiAdjustmentRange: { min: 0, max: 15 },
    optimum: 6,
    currentValue: 6,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "compressor.makeup_gain_db": {
    id: "compressor.makeup_gain_db",
    name: "Compressor Makeup Gain",
    category: "compressor",
    type: "numeric" as const,
    description: "Gain applied after compression",
    unit: "dB",
    validRange: { min: 0, max: 30 },
    recommendedRange: { min: 0, max: 12 },
    aiAdjustmentRange: { min: 0, max: 20 },
    optimum: 6,
    currentValue: 6,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Limiter
  "limiter.enabled": {
    id: "limiter.enabled",
    name: "Limiter Enabled",
    category: "limiter",
    type: "boolean" as const,
    description: "Enable or disable output limiter",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "limiter.threshold_dbfs": {
    id: "limiter.threshold_dbfs",
    name: "Limiter Threshold",
    category: "limiter",
    type: "numeric" as const,
    description: "Peak level ceiling for output limiter",
    unit: "dBFS",
    validRange: { min: -12, max: 0 },
    recommendedRange: { min: -6, max: -1 },
    aiAdjustmentRange: { min: -9, max: 0 },
    optimum: -3,
    currentValue: -3,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "limiter.attack_time_ms": {
    id: "limiter.attack_time_ms",
    name: "Limiter Attack Time",
    category: "limiter",
    type: "numeric" as const,
    description: "Fast attack time for peak limiting",
    unit: "ms",
    validRange: { min: 0.01, max: 10 },
    recommendedRange: { min: 0.1, max: 2 },
    aiAdjustmentRange: { min: 0.05, max: 5 },
    optimum: 0.5,
    currentValue: 0.5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "limiter.release_time_ms": {
    id: "limiter.release_time_ms",
    name: "Limiter Release Time",
    category: "limiter",
    type: "numeric" as const,
    description: "Release time for peak limiter",
    unit: "ms",
    validRange: { min: 10, max: 500 },
    recommendedRange: { min: 50, max: 200 },
    aiAdjustmentRange: { min: 20, max: 300 },
    optimum: 100,
    currentValue: 100,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Equalizer (EQ)
  "eq.enabled": {
    id: "eq.enabled",
    name: "EQ Enabled",
    category: "eq",
    type: "boolean" as const,
    description: "Enable or disable EQ filter",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false, true],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "eq.preset": {
    id: "eq.preset",
    name: "EQ Preset",
    category: "eq",
    type: "enum" as const,
    description: "Named EQ preset for voice/audio shaping",
    unit: "enum",
    validValues: ["flat", "voice", "bright", "dark", "custom"],
    recommendedValues: ["voice"],
    aiAllowedValues: ["flat", "voice", "bright", "dark"],
    currentValue: "voice",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "eq.low_gain_db": {
    id: "eq.low_gain_db",
    name: "EQ Low Frequency Gain",
    category: "eq",
    type: "numeric" as const,
    description: "Gain adjustment for low frequencies",
    unit: "dB",
    validRange: { min: -12, max: 12 },
    recommendedRange: { min: -6, max: 6 },
    aiAdjustmentRange: { min: -9, max: 9 },
    optimum: 0,
    currentValue: 0,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "eq.mid_gain_db": {
    id: "eq.mid_gain_db",
    name: "EQ Mid Frequency Gain",
    category: "eq",
    type: "numeric" as const,
    description: "Gain adjustment for mid frequencies",
    unit: "dB",
    validRange: { min: -12, max: 12 },
    recommendedRange: { min: -6, max: 6 },
    aiAdjustmentRange: { min: -9, max: 9 },
    optimum: 2,
    currentValue: 2,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "eq.high_gain_db": {
    id: "eq.high_gain_db",
    name: "EQ High Frequency Gain",
    category: "eq",
    type: "numeric" as const,
    description: "Gain adjustment for high frequencies",
    unit: "dB",
    validRange: { min: -12, max: 12 },
    recommendedRange: { min: -6, max: 6 },
    aiAdjustmentRange: { min: -9, max: 9 },
    optimum: 0,
    currentValue: 0,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "eq.low_freq_hz": {
    id: "eq.low_freq_hz",
    name: "EQ Low Frequency Center",
    category: "eq",
    type: "numeric" as const,
    description: "Center frequency for low band",
    unit: "Hz",
    validRange: { min: 50, max: 500 },
    recommendedRange: { min: 100, max: 300 },
    aiAdjustmentRange: { min: 80, max: 400 },
    optimum: 200,
    currentValue: 200,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "eq.mid_freq_hz": {
    id: "eq.mid_freq_hz",
    name: "EQ Mid Frequency Center",
    category: "eq",
    type: "numeric" as const,
    description: "Center frequency for mid band",
    unit: "Hz",
    validRange: { min: 500, max: 5000 },
    recommendedRange: { min: 1000, max: 3000 },
    aiAdjustmentRange: { min: 800, max: 4000 },
    optimum: 2000,
    currentValue: 2000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "eq.high_freq_hz": {
    id: "eq.high_freq_hz",
    name: "EQ High Frequency Center",
    category: "eq",
    type: "numeric" as const,
    description: "Center frequency for high band",
    unit: "Hz",
    validRange: { min: 3000, max: 16000 },
    recommendedRange: { min: 5000, max: 10000 },
    aiAdjustmentRange: { min: 4000, max: 12000 },
    optimum: 8000,
    currentValue: 8000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Buffer & Jitter
  "buffer.size_ms": {
    id: "buffer.size_ms",
    name: "Buffer Size",
    category: "buffer",
    type: "numeric" as const,
    description: "Base buffer size for playout/processing",
    unit: "ms",
    validRange: { min: 20, max: 2000 },
    recommendedRange: { min: 80, max: 400 },
    aiAdjustmentRange: { min: 40, max: 800 },
    optimum: 200,
    currentValue: 180,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.jitter_size_ms": {
    id: "buffer.jitter_size_ms",
    name: "Jitter Buffer Size",
    category: "buffer",
    type: "numeric" as const,
    description: "Target size of jitter buffer",
    unit: "ms",
    validRange: { min: 0, max: 500 },
    recommendedRange: { min: 20, max: 120 },
    aiAdjustmentRange: { min: 10, max: 200 },
    optimum: 60,
    currentValue: 70,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.playout_delay_ms": {
    id: "buffer.playout_delay_ms",
    name: "Playout Delay",
    category: "buffer",
    type: "numeric" as const,
    description: "Additional playout delay to smooth jitter",
    unit: "ms",
    validRange: { min: 0, max: 500 },
    recommendedRange: { min: 20, max: 120 },
    aiAdjustmentRange: { min: 10, max: 200 },
    optimum: 60,
    currentValue: 65,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.adaptive_mode": {
    id: "buffer.adaptive_mode",
    name: "Adaptive Buffer Mode",
    category: "buffer",
    type: "boolean" as const,
    description: "Enable adaptive buffer resizing",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.min_size_ms": {
    id: "buffer.min_size_ms",
    name: "Min Buffer Size",
    category: "buffer",
    type: "numeric" as const,
    description: "Lower bound for adaptive buffer size",
    unit: "ms",
    validRange: { min: 10, max: 200 },
    recommendedRange: { min: 20, max: 80 },
    aiAdjustmentRange: { min: 10, max: 150 },
    optimum: 40,
    currentValue: 50,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.max_size_ms": {
    id: "buffer.max_size_ms",
    name: "Max Buffer Size",
    category: "buffer",
    type: "numeric" as const,
    description: "Upper bound for adaptive buffer size",
    unit: "ms",
    validRange: { min: 100, max: 5000 },
    recommendedRange: { min: 500, max: 2000 },
    aiAdjustmentRange: { min: 300, max: 3000 },
    optimum: 1000,
    currentValue: 1200,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.target_level_pct": {
    id: "buffer.target_level_pct",
    name: "Target Buffer Level",
    category: "buffer",
    type: "numeric" as const,
    description: "Target buffer fill level as percentage",
    unit: "%",
    validRange: { min: 10, max: 90 },
    recommendedRange: { min: 40, max: 70 },
    aiAdjustmentRange: { min: 30, max: 80 },
    optimum: 55,
    currentValue: 60,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.underrun_threshold_ms": {
    id: "buffer.underrun_threshold_ms",
    name: "Underrun Threshold",
    category: "buffer",
    type: "numeric" as const,
    description: "Threshold to consider buffer underrun",
    unit: "ms",
    validRange: { min: 0, max: 200 },
    recommendedRange: { min: 5, max: 50 },
    aiAdjustmentRange: { min: 2, max: 100 },
    optimum: 20,
    currentValue: 25,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.overrun_threshold_ms": {
    id: "buffer.overrun_threshold_ms",
    name: "Overrun Threshold",
    category: "buffer",
    type: "numeric" as const,
    description: "Threshold to consider buffer overrun",
    unit: "ms",
    validRange: { min: 50, max: 5000 },
    recommendedRange: { min: 200, max: 1500 },
    aiAdjustmentRange: { min: 100, max: 3000 },
    optimum: 800,
    currentValue: 900,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.growth_rate": {
    id: "buffer.growth_rate",
    name: "Buffer Growth Rate",
    category: "buffer",
    type: "numeric" as const,
    description: "Multiplicative growth factor when expanding buffer",
    unit: "factor",
    validRange: { min: 1.0, max: 5.0 },
    recommendedRange: { min: 1.2, max: 2.0 },
    aiAdjustmentRange: { min: 1.0, max: 3.0 },
    optimum: 1.5,
    currentValue: 1.4,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.shrink_rate": {
    id: "buffer.shrink_rate",
    name: "Buffer Shrink Rate",
    category: "buffer",
    type: "numeric" as const,
    description: "Multiplicative factor when shrinking buffer",
    unit: "factor",
    validRange: { min: 0.5, max: 1.0 },
    recommendedRange: { min: 0.8, max: 0.98 },
    aiAdjustmentRange: { min: 0.7, max: 1.0 },
    optimum: 0.9,
    currentValue: 0.88,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.packet_loss_concealment": {
    id: "buffer.packet_loss_concealment",
    name: "Packet Loss Concealment",
    category: "buffer",
    type: "boolean" as const,
    description: "Enable packet loss concealment algorithms",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.fec_enabled": {
    id: "buffer.fec_enabled",
    name: "FEC Enabled",
    category: "buffer",
    type: "boolean" as const,
    description: "Enable forward error correction for packets",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false, true],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.interleaving_depth": {
    id: "buffer.interleaving_depth",
    name: "Interleaving Depth",
    category: "buffer",
    type: "numeric" as const,
    description: "Packet interleaving depth for loss robustness",
    unit: "packets",
    validRange: { min: 0, max: 10 },
    recommendedRange: { min: 0, max: 4 },
    aiAdjustmentRange: { min: 0, max: 6 },
    optimum: 2,
    currentValue: 2,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "buffer.reorder_tolerance_ms": {
    id: "buffer.reorder_tolerance_ms",
    name: "Reorder Tolerance",
    category: "buffer",
    type: "numeric" as const,
    description: "Time window to accept out-of-order packets",
    unit: "ms",
    validRange: { min: 0, max: 200 },
    recommendedRange: { min: 20, max: 80 },
    aiAdjustmentRange: { min: 10, max: 150 },
    optimum: 50,
    currentValue: 55,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Network / RTP
  "network.codec": {
    id: "network.codec",
    name: "Audio Codec",
    category: "network",
    type: "enum" as const,
    description: "Primary audio codec for RTP stream",
    unit: "enum",
    validValues: ["opus", "pcmu", "pcma", "g722", "g729"],
    recommendedValues: ["opus"],
    aiAllowedValues: ["opus", "pcmu", "pcma"],
    currentValue: "opus",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.bitrate_kbps": {
    id: "network.bitrate_kbps",
    name: "Bitrate",
    category: "network",
    type: "numeric" as const,
    description: "Target codec bitrate",
    unit: "kbps",
    validRange: { min: 6, max: 256 },
    recommendedRange: { min: 32, max: 96 },
    aiAdjustmentRange: { min: 24, max: 128 },
    optimum: 64,
    currentValue: 68,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.packet_size_ms": {
    id: "network.packet_size_ms",
    name: "Packet Size",
    category: "network",
    type: "numeric" as const,
    description: "RTP packetization interval",
    unit: "ms",
    validRange: { min: 10, max: 60 },
    recommendedRange: { min: 20, max: 40 },
    aiAdjustmentRange: { min: 10, max: 60 },
    optimum: 20,
    currentValue: 20,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.dtx_enabled": {
    id: "network.dtx_enabled",
    name: "DTX Enabled",
    category: "network",
    type: "boolean" as const,
    description: "Enable discontinuous transmission in silence",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false, true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.vad_mode": {
    id: "network.vad_mode",
    name: "VAD Mode",
    category: "network",
    type: "enum" as const,
    description: "Voice activity detection aggressiveness",
    unit: "enum",
    validValues: ["off", "low", "medium", "high", "very_high"],
    recommendedValues: ["medium"],
    aiAllowedValues: ["low", "medium", "high"],
    currentValue: "medium",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.rtp.port": {
    id: "network.rtp.port",
    name: "RTP Port",
    category: "network",
    type: "numeric" as const,
    description: "UDP port for RTP media stream",
    unit: "port",
    validRange: { min: 1024, max: 65535 },
    recommendedRange: { min: 10000, max: 20000 },
    aiAdjustmentRange: { min: 10000, max: 20000 },
    optimum: 10000,
    currentValue: 10000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.rtcp.enabled": {
    id: "network.rtcp.enabled",
    name: "RTCP Enabled",
    category: "network",
    type: "boolean" as const,
    description: "Enable RTCP for quality feedback",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.rtcp.interval_ms": {
    id: "network.rtcp.interval_ms",
    name: "RTCP Interval",
    category: "network",
    type: "numeric" as const,
    description: "Interval for sending RTCP reports",
    unit: "ms",
    validRange: { min: 100, max: 10000 },
    recommendedRange: { min: 1000, max: 5000 },
    aiAdjustmentRange: { min: 500, max: 8000 },
    optimum: 5000,
    currentValue: 5000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.dscp_value": {
    id: "network.dscp_value",
    name: "DSCP Value",
    category: "network",
    type: "numeric" as const,
    description: "DiffServ code point for QoS marking",
    unit: "value",
    validRange: { min: 0, max: 63 },
    recommendedRange: { min: 40, max: 46 },
    aiAdjustmentRange: { min: 32, max: 56 },
    optimum: 46,
    currentValue: 46,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.tos_value": {
    id: "network.tos_value",
    name: "ToS Value",
    category: "network",
    type: "numeric" as const,
    description: "Type of Service value for IP header",
    unit: "value",
    validRange: { min: 0, max: 255 },
    recommendedRange: { min: 160, max: 184 },
    aiAdjustmentRange: { min: 128, max: 224 },
    optimum: 184,
    currentValue: 184,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "network.mtu_bytes": {
    id: "network.mtu_bytes",
    name: "MTU Size",
    category: "network",
    type: "numeric" as const,
    description: "Maximum transmission unit size",
    unit: "bytes",
    validRange: { min: 576, max: 9000 },
    recommendedRange: { min: 1200, max: 1500 },
    aiAdjustmentRange: { min: 1000, max: 1500 },
    optimum: 1500,
    currentValue: 1500,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Sampling & Format
  "format.sample_rate_hz": {
    id: "format.sample_rate_hz",
    name: "Sample Rate",
    category: "format",
    type: "numeric" as const,
    description: "Audio sample rate in Hz",
    unit: "Hz",
    validRange: { min: 8000, max: 48000 },
    recommendedRange: { min: 16000, max: 48000 },
    aiAdjustmentRange: { min: 16000, max: 48000 },
    optimum: 48000,
    currentValue: 48000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "format.bit_depth": {
    id: "format.bit_depth",
    name: "Bit Depth",
    category: "format",
    type: "numeric" as const,
    description: "Audio bit depth",
    unit: "bits",
    validRange: { min: 8, max: 32 },
    recommendedRange: { min: 16, max: 24 },
    aiAdjustmentRange: { min: 16, max: 24 },
    optimum: 16,
    currentValue: 16,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "format.channels": {
    id: "format.channels",
    name: "Channel Count",
    category: "format",
    type: "numeric" as const,
    description: "Number of audio channels",
    unit: "channels",
    validRange: { min: 1, max: 2 },
    recommendedRange: { min: 1, max: 1 },
    aiAdjustmentRange: { min: 1, max: 2 },
    optimum: 1,
    currentValue: 1,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // High-Pass Filter
  "hpf.enabled": {
    id: "hpf.enabled",
    name: "HPF Enabled",
    category: "filter",
    type: "boolean" as const,
    description: "Enable high-pass filter to remove low-frequency rumble",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "hpf.cutoff_hz": {
    id: "hpf.cutoff_hz",
    name: "HPF Cutoff Frequency",
    category: "filter",
    type: "numeric" as const,
    description: "High-pass filter cutoff frequency",
    unit: "Hz",
    validRange: { min: 20, max: 500 },
    recommendedRange: { min: 80, max: 200 },
    aiAdjustmentRange: { min: 50, max: 300 },
    optimum: 100,
    currentValue: 100,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Low-Pass Filter
  "lpf.enabled": {
    id: "lpf.enabled",
    name: "LPF Enabled",
    category: "filter",
    type: "boolean" as const,
    description: "Enable low-pass filter for bandwidth limitation",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "lpf.cutoff_hz": {
    id: "lpf.cutoff_hz",
    name: "LPF Cutoff Frequency",
    category: "filter",
    type: "numeric" as const,
    description: "Low-pass filter cutoff frequency",
    unit: "Hz",
    validRange: { min: 3000, max: 20000 },
    recommendedRange: { min: 8000, max: 16000 },
    aiAdjustmentRange: { min: 4000, max: 20000 },
    optimum: 16000,
    currentValue: 16000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // De-esser
  "deesser.enabled": {
    id: "deesser.enabled",
    name: "De-esser Enabled",
    category: "deesser",
    type: "boolean" as const,
    description: "Enable de-esser to reduce harsh sibilance",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "deesser.frequency_hz": {
    id: "deesser.frequency_hz",
    name: "De-esser Frequency",
    category: "deesser",
    type: "numeric" as const,
    description: "Center frequency for sibilance detection",
    unit: "Hz",
    validRange: { min: 4000, max: 12000 },
    recommendedRange: { min: 6000, max: 9000 },
    aiAdjustmentRange: { min: 5000, max: 10000 },
    optimum: 7500,
    currentValue: 7500,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "deesser.threshold_db": {
    id: "deesser.threshold_db",
    name: "De-esser Threshold",
    category: "deesser",
    type: "numeric" as const,
    description: "Level above which de-essing is applied",
    unit: "dB",
    validRange: { min: -40, max: 0 },
    recommendedRange: { min: -24, max: -12 },
    aiAdjustmentRange: { min: -30, max: -6 },
    optimum: -18,
    currentValue: -18,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "deesser.reduction_db": {
    id: "deesser.reduction_db",
    name: "De-esser Reduction",
    category: "deesser",
    type: "numeric" as const,
    description: "Amount of sibilance reduction",
    unit: "dB",
    validRange: { min: -20, max: 0 },
    recommendedRange: { min: -12, max: -3 },
    aiAdjustmentRange: { min: -15, max: 0 },
    optimum: -6,
    currentValue: -6,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Gate
  "gate.enabled": {
    id: "gate.enabled",
    name: "Gate Enabled",
    category: "gate",
    type: "boolean" as const,
    description: "Enable noise gate",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gate.threshold_db": {
    id: "gate.threshold_db",
    name: "Gate Threshold",
    category: "gate",
    type: "numeric" as const,
    description: "Level below which gate closes",
    unit: "dB",
    validRange: { min: -80, max: -10 },
    recommendedRange: { min: -60, max: -30 },
    aiAdjustmentRange: { min: -70, max: -20 },
    optimum: -45,
    currentValue: -45,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gate.attack_time_ms": {
    id: "gate.attack_time_ms",
    name: "Gate Attack Time",
    category: "gate",
    type: "numeric" as const,
    description: "Time for gate to open",
    unit: "ms",
    validRange: { min: 0.1, max: 50 },
    recommendedRange: { min: 1, max: 10 },
    aiAdjustmentRange: { min: 0.5, max: 20 },
    optimum: 3,
    currentValue: 3,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gate.release_time_ms": {
    id: "gate.release_time_ms",
    name: "Gate Release Time",
    category: "gate",
    type: "numeric" as const,
    description: "Time for gate to close",
    unit: "ms",
    validRange: { min: 10, max: 1000 },
    recommendedRange: { min: 50, max: 300 },
    aiAdjustmentRange: { min: 20, max: 500 },
    optimum: 150,
    currentValue: 150,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gate.hold_time_ms": {
    id: "gate.hold_time_ms",
    name: "Gate Hold Time",
    category: "gate",
    type: "numeric" as const,
    description: "Time gate stays open after signal drops below threshold",
    unit: "ms",
    validRange: { min: 0, max: 1000 },
    recommendedRange: { min: 50, max: 300 },
    aiAdjustmentRange: { min: 20, max: 500 },
    optimum: 100,
    currentValue: 100,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gate.range_db": {
    id: "gate.range_db",
    name: "Gate Range",
    category: "gate",
    type: "numeric" as const,
    description: "Maximum attenuation when gate is closed",
    unit: "dB",
    validRange: { min: -80, max: 0 },
    recommendedRange: { min: -40, max: -20 },
    aiAdjustmentRange: { min: -60, max: -10 },
    optimum: -30,
    currentValue: -30,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Expander
  "expander.enabled": {
    id: "expander.enabled",
    name: "Expander Enabled",
    category: "expander",
    type: "boolean" as const,
    description: "Enable downward expander for dynamic range expansion",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "expander.threshold_db": {
    id: "expander.threshold_db",
    name: "Expander Threshold",
    category: "expander",
    type: "numeric" as const,
    description: "Level below which expansion occurs",
    unit: "dB",
    validRange: { min: -60, max: 0 },
    recommendedRange: { min: -40, max: -20 },
    aiAdjustmentRange: { min: -50, max: -10 },
    optimum: -30,
    currentValue: -30,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "expander.ratio": {
    id: "expander.ratio",
    name: "Expander Ratio",
    category: "expander",
    type: "numeric" as const,
    description: "Expansion ratio for signals below threshold",
    unit: "ratio",
    validRange: { min: 1.0, max: 10.0 },
    recommendedRange: { min: 1.5, max: 4.0 },
    aiAdjustmentRange: { min: 1.0, max: 6.0 },
    optimum: 2.0,
    currentValue: 2.0,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "expander.attack_time_ms": {
    id: "expander.attack_time_ms",
    name: "Expander Attack Time",
    category: "expander",
    type: "numeric" as const,
    description: "Time for expander to engage",
    unit: "ms",
    validRange: { min: 0.1, max: 50 },
    recommendedRange: { min: 1, max: 10 },
    aiAdjustmentRange: { min: 0.5, max: 20 },
    optimum: 3,
    currentValue: 3,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "expander.release_time_ms": {
    id: "expander.release_time_ms",
    name: "Expander Release Time",
    category: "expander",
    type: "numeric" as const,
    description: "Time for expander to release",
    unit: "ms",
    validRange: { min: 10, max: 1000 },
    recommendedRange: { min: 50, max: 300 },
    aiAdjustmentRange: { min: 20, max: 500 },
    optimum: 150,
    currentValue: 150,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Transient Shaper
  "transient.enabled": {
    id: "transient.enabled",
    name: "Transient Shaper Enabled",
    category: "transient",
    type: "boolean" as const,
    description: "Enable transient shaper for attack/sustain control",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "transient.attack_gain_db": {
    id: "transient.attack_gain_db",
    name: "Transient Attack Gain",
    category: "transient",
    type: "numeric" as const,
    description: "Gain adjustment for transient attacks",
    unit: "dB",
    validRange: { min: -12, max: 12 },
    recommendedRange: { min: -6, max: 6 },
    aiAdjustmentRange: { min: -9, max: 9 },
    optimum: 0,
    currentValue: 0,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "transient.sustain_gain_db": {
    id: "transient.sustain_gain_db",
    name: "Transient Sustain Gain",
    category: "transient",
    type: "numeric" as const,
    description: "Gain adjustment for sustain portion",
    unit: "dB",
    validRange: { min: -12, max: 12 },
    recommendedRange: { min: -6, max: 6 },
    aiAdjustmentRange: { min: -9, max: 9 },
    optimum: 0,
    currentValue: 0,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Timing & Synchronization
  "timing.clock_source": {
    id: "timing.clock_source",
    name: "Clock Source",
    category: "timing",
    type: "enum" as const,
    description: "Audio clock source for synchronization",
    unit: "enum",
    validValues: ["internal", "external", "ntp", "ptp"],
    recommendedValues: ["internal"],
    aiAllowedValues: ["internal", "external"],
    currentValue: "internal",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "timing.drift_correction": {
    id: "timing.drift_correction",
    name: "Drift Correction Enabled",
    category: "timing",
    type: "boolean" as const,
    description: "Enable clock drift correction",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "timing.timestamp_mode": {
    id: "timing.timestamp_mode",
    name: "Timestamp Mode",
    category: "timing",
    type: "enum" as const,
    description: "RTP timestamp generation mode",
    unit: "enum",
    validValues: ["realtime", "incremental", "ntp"],
    recommendedValues: ["realtime"],
    aiAllowedValues: ["realtime", "incremental"],
    currentValue: "realtime",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Monitoring & Diagnostics
  "monitoring.metrics_enabled": {
    id: "monitoring.metrics_enabled",
    name: "Metrics Collection Enabled",
    category: "monitoring",
    type: "boolean" as const,
    description: "Enable collection of audio/network metrics",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [true],
    aiAllowedValues: [false, true],
    currentValue: true,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "monitoring.sample_rate_ms": {
    id: "monitoring.sample_rate_ms",
    name: "Metrics Sample Rate",
    category: "monitoring",
    type: "numeric" as const,
    description: "Interval for collecting metrics",
    unit: "ms",
    validRange: { min: 100, max: 10000 },
    recommendedRange: { min: 500, max: 2000 },
    aiAdjustmentRange: { min: 200, max: 5000 },
    optimum: 1000,
    currentValue: 1000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "monitoring.logging_level": {
    id: "monitoring.logging_level",
    name: "Logging Level",
    category: "monitoring",
    type: "enum" as const,
    description: "Verbosity level for system logging",
    unit: "enum",
    validValues: ["error", "warn", "info", "debug", "trace"],
    recommendedValues: ["info"],
    aiAllowedValues: ["warn", "info", "debug"],
    currentValue: "info",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Gateway knobs
  "gateway.sample_rate_hz": {
    id: "gateway.sample_rate_hz",
    name: "Gateway Sample Rate",
    category: "gateway",
    type: "numeric" as const,
    description: "Sample rate at gateway.",
    unit: "Hz",
    validRange: { min: 8000, max: 48000 },
    recommendedRange: { min: 16000, max: 24000 },
    aiAdjustmentRange: { min: 8000, max: 48000 },
    optimum: 16000,
    currentValue: 16000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gateway.channels": {
    id: "gateway.channels",
    name: "Gateway Channels",
    category: "gateway",
    type: "numeric" as const,
    description: "Number of audio channels",
    unit: "channels",
    validRange: { min: 1, max: 8 },
    recommendedRange: { min: 1, max: 2 },
    aiAdjustmentRange: { min: 1, max: 2 },
    optimum: 1,
    currentValue: 1,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gateway.encoding": {
    id: "gateway.encoding",
    name: "Gateway Encoding",
    category: "gateway",
    type: "enum" as const,
    description: "Audio encoding format on gateway link",
    unit: "enum",
    validValues: ["pcm", "opus", "mulaw", "alaw"],
    recommendedValues: ["pcm", "opus"],
    aiAllowedValues: ["pcm", "opus"],
    currentValue: "pcm",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gateway.stream_timeout_ms": {
    id: "gateway.stream_timeout_ms",
    name: "Stream Timeout",
    category: "gateway",
    type: "numeric" as const,
    description: "Inactivity timeout for media stream",
    unit: "ms",
    validRange: { min: 1000, max: 600000 },
    recommendedRange: { min: 30000, max: 180000 },
    aiAdjustmentRange: { min: 10000, max: 300000 },
    optimum: 60000,
    currentValue: 60000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "gateway.debug_mode": {
    id: "gateway.debug_mode",
    name: "Gateway Debug Mode",
    category: "gateway",
    type: "boolean" as const,
    description: "Enable verbose debug logging in gateway",
    unit: "boolean",
    validValues: [false, true],
    recommendedValues: [false],
    aiAllowedValues: [false, true],
    currentValue: false,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Deepgram (STT) knobs
  "deepgram.model": {
    id: "deepgram.model",
    name: "Deepgram Model",
    category: "stt",
    type: "enum" as const,
    description: "Deepgram model identifier",
    unit: "enum",
    validValues: ["nova-2", "nova-2-meeting", "nova-2-phone", "enhance-general"],
    recommendedValues: ["nova-2"],
    aiAllowedValues: ["nova-2", "nova-2-meeting", "nova-2-phone", "enhance-general"],
    currentValue: "nova-2",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "deepgram.endpointing": {
    id: "deepgram.endpointing",
    name: "Deepgram Endpointing",
    category: "stt",
    type: "numeric" as const,
    description: "Endpointing timeout after speech to close segment",
    unit: "ms",
    validRange: { min: 0, max: 2000 },
    recommendedRange: { min: 200, max: 800 },
    aiAdjustmentRange: { min: 100, max: 1500 },
    optimum: 500,
    currentValue: 500,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // Translation knobs
  "translation.source_lang": {
    id: "translation.source_lang",
    name: "Translation Source Language",
    category: "translation",
    type: "enum" as const,
    description: "Source language code",
    unit: "enum",
    validValues: ["en", "es", "fr", "de", "ja", "zh"],
    recommendedValues: ["en"],
    aiAllowedValues: ["en", "es", "fr", "de"],
    currentValue: "en",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "translation.target_lang": {
    id: "translation.target_lang",
    name: "Translation Target Language",
    category: "translation",
    type: "enum" as const,
    description: "Target language code",
    unit: "enum",
    validValues: ["en", "es", "fr", "de", "ja", "zh"],
    recommendedValues: ["es"],
    aiAllowedValues: ["en", "es", "fr", "de"],
    currentValue: "es",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "translation.formality": {
    id: "translation.formality",
    name: "Translation Formality",
    category: "translation",
    type: "enum" as const,
    description: "Formality level of translation",
    unit: "enum",
    validValues: ["default", "more", "less"],
    recommendedValues: ["default"],
    aiAllowedValues: ["default", "more", "less"],
    currentValue: "default",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "translation.max_length": {
    id: "translation.max_length",
    name: "Translation Max Length",
    category: "translation",
    type: "numeric" as const,
    description: "Maximum characters per translation request",
    unit: "characters",
    validRange: { min: 1, max: 30000 },
    recommendedRange: { min: 100, max: 8000 },
    aiAdjustmentRange: { min: 50, max: 12000 },
    optimum: 5000,
    currentValue: 5000,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },

  // TTS knobs
  "tts.voice_id": {
    id: "tts.voice_id",
    name: "TTS Voice ID",
    category: "tts",
    type: "enum" as const,
    description: "TTS voice identifier",
    unit: "enum",
    validValues: ["rachel", "josh", "bella", "adam"],
    recommendedValues: ["rachel"],
    aiAllowedValues: ["rachel", "josh", "bella"],
    currentValue: "rachel",
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "tts.stability": {
    id: "tts.stability",
    name: "TTS Stability",
    category: "tts",
    type: "numeric" as const,
    description: "Stability vs variability of TTS output",
    unit: "float",
    validRange: { min: 0.0, max: 1.0 },
    recommendedRange: { min: 0.3, max: 0.8 },
    aiAdjustmentRange: { min: 0.1, max: 0.9 },
    optimum: 0.5,
    currentValue: 0.5,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
  "tts.similarity_boost": {
    id: "tts.similarity_boost",
    name: "TTS Similarity Boost",
    category: "tts",
    type: "numeric" as const,
    description: "How strongly to match reference voice timbre",
    unit: "float",
    validRange: { min: 0.0, max: 1.0 },
    recommendedRange: { min: 0.5, max: 0.9 },
    aiAdjustmentRange: { min: 0.2, max: 1.0 },
    optimum: 0.75,
    currentValue: 0.75,
    stations: ["STATION_1", "STATION_2", "STATION_3", "STATION_4", "STATION_9", "STATION_10", "STATION_11"], // Added stations field
  },
} as const

export type KnobId = keyof typeof KNOBS_CONFIG
export type KnobConfig = (typeof KNOBS_CONFIG)[KnobId]
