// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { AudioFormatType } from "./AudioFormatType.mjs";
export const AudioEncoding = core.serialization.object({
    format: AudioFormatType,
    sampleRate: core.serialization.property("sample_rate", core.serialization.number()),
});
