// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const FormatWav = core.serialization.object({
    type: core.serialization.stringLiteral("wav"),
});
