// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { FormatMp3 } from "./FormatMp3.mjs";
import { FormatPcm } from "./FormatPcm.mjs";
import { FormatWav } from "./FormatWav.mjs";
export const Format = core.serialization.undiscriminatedUnion([FormatMp3, FormatPcm, FormatWav]);
