// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
export const FormatPcm = core.serialization.object({
    type: core.serialization.stringLiteral("pcm"),
});
