// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { PostedUtteranceVoice } from "./PostedUtteranceVoice.mjs";
export const PostedUtterance = core.serialization.object({
    description: core.serialization.string().optional(),
    speed: core.serialization.number().optional(),
    text: core.serialization.string(),
    trailingSilence: core.serialization.property("trailing_silence", core.serialization.number().optional()),
    voice: PostedUtteranceVoice.optional(),
});
