// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { PostedUtteranceVoiceWithId } from "./PostedUtteranceVoiceWithId.mjs";
import { PostedUtteranceVoiceWithName } from "./PostedUtteranceVoiceWithName.mjs";
export const PostedUtteranceVoice = core.serialization.undiscriminatedUnion([PostedUtteranceVoiceWithId, PostedUtteranceVoiceWithName]);
