// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { PostedUtterance } from "./PostedUtterance.mjs";
export const PostedContextWithUtterances = core.serialization.object({
    utterances: core.serialization.list(PostedUtterance),
});
