// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { VoiceProvider } from "./VoiceProvider.mjs";
export const PostedUtteranceVoiceWithName = core.serialization.object({
    name: core.serialization.string(),
    provider: VoiceProvider.optional(),
});
