// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { PostedContextWithGenerationId } from "./PostedContextWithGenerationId.mjs";
import { PostedContextWithUtterances } from "./PostedContextWithUtterances.mjs";
export const PostedContext = core.serialization.undiscriminatedUnion([PostedContextWithGenerationId, PostedContextWithUtterances]);
