// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { VoiceProvider } from "./VoiceProvider.mjs";
export const ReturnVoice = core.serialization.object({
    compatibleOctaveModels: core.serialization.property("compatible_octave_models", core.serialization.list(core.serialization.string()).optional()),
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    provider: VoiceProvider.optional(),
});
