// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { ReturnGeneration } from "./ReturnGeneration.mjs";
export const ReturnTts = core.serialization.object({
    generations: core.serialization.list(ReturnGeneration),
    requestId: core.serialization.property("request_id", core.serialization.string().optional()),
});
