// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { Timestamp } from "./Timestamp.mjs";
export const Snippet = core.serialization.object({
    audio: core.serialization.string(),
    generationId: core.serialization.property("generation_id", core.serialization.string()),
    id: core.serialization.string(),
    text: core.serialization.string(),
    timestamps: core.serialization.list(Timestamp),
    transcribedText: core.serialization.property("transcribed_text", core.serialization.string().optional()),
    utteranceIndex: core.serialization.property("utterance_index", core.serialization.number().optional()),
});
