// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { MillisecondInterval } from "./MillisecondInterval.mjs";
import { TimestampType } from "./TimestampType.mjs";
export const Timestamp = core.serialization.object({
    text: core.serialization.string(),
    time: MillisecondInterval,
    type: TimestampType,
});
