// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { Timestamp } from "./Timestamp.mjs";
export const TimestampMessage = core.serialization.object({
    generationId: core.serialization.property("generation_id", core.serialization.string()),
    requestId: core.serialization.property("request_id", core.serialization.string()),
    snippetId: core.serialization.property("snippet_id", core.serialization.string()),
    timestamp: Timestamp,
    type: core.serialization.stringLiteral("timestamp"),
});
