// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../core/index.mjs";
import { SnippetAudioChunk } from "./SnippetAudioChunk.mjs";
import { TimestampMessage } from "./TimestampMessage.mjs";
export const TtsOutput = core.serialization.undiscriminatedUnion([SnippetAudioChunk, TimestampMessage]);
