// This file was auto-generated by Fern from our API Definition.
import { ReturnUserDefinedTool } from "../../../types/ReturnUserDefinedTool.mjs";
export const Response = ReturnUserDefinedTool.optional();
