// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../core/index.mjs";
export const PostedUserDefinedTool = core.serialization.object({
    description: core.serialization.string().optional(),
    fallbackContent: core.serialization.property("fallback_content", core.serialization.string().optional()),
    name: core.serialization.string(),
    parameters: core.serialization.string(),
    versionDescription: core.serialization.property("version_description", core.serialization.string().optional()),
});
