"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExpressionMeasurement = void 0;
const Client_js_1 = require("../resources/batch/client/Client.js");
class ExpressionMeasurement {
    constructor(_options = {}) {
        this._options = _options;
    }
    get batch() {
        var _a;
        return ((_a = this._batch) !== null && _a !== void 0 ? _a : (this._batch = new Client_js_1.Batch(this._options)));
    }
}
exports.ExpressionMeasurement = ExpressionMeasurement;
