"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.Response = void 0;
const ReturnPrompt_js_1 = require("../../../types/ReturnPrompt.js");
exports.Response = ReturnPrompt_js_1.ReturnPrompt.optional();
