// This file was auto-generated by Fern from our API Definition.
import * as core from "../../../../../../../core/index.mjs";
import { SubscribeEvent } from "../../../../types/SubscribeEvent.mjs";
export const ChatSocketResponse = core.serialization.undiscriminatedUnion([SubscribeEvent]);
