export interface KnobDefinition {
  id: string
  name: string
  description: string
  unit: string
  type: "number" | "boolean" | "enum"
  validValues?: string[]
  validRange?: { min: number; max: number }
  recommendedValues?: string[]
  recommendedRange?: { min: number; max: number }
  aiAllowedValues?: string[]
  aiAdjustmentRange?: { min: number; max: number }
  category:
    | "agc"
    | "aec"
    | "nr"
    | "compressor"
    | "limiter"
    | "eq"
    | "buffer"
    | "network"
    | "asterisk"
    | "gateway"
    | "deepgram"
    | "translation"
    | "tts"
}

export const KNOB_DEFINITIONS: Record<string, KnobDefinition> = {
  // AGC (6 knobs)
  "agc.enabled": {
    id: "agc.enabled",
    name: "AGC Enabled",
    description: "Enable or disable automatic gain control on the input.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "agc",
  },
  "agc.target_level_dbfs": {
    id: "agc.target_level_dbfs",
    name: "AGC Target Level",
    description: "Target RMS level relative to full scale for AGC.",
    unit: "dBFS",
    type: "number",
    validRange: { min: -60, max: 0 },
    recommendedRange: { min: -24, max: -14 },
    aiAdjustmentRange: { min: -30, max: -10 },
    category: "agc",
  },
  "agc.compression_ratio": {
    id: "agc.compression_ratio",
    name: "AGC Compression Ratio",
    description: "Gain compression ratio used by AGC.",
    unit: "ratio",
    type: "number",
    validRange: { min: 1.0, max: 10.0 },
    recommendedRange: { min: 2.0, max: 6.0 },
    aiAdjustmentRange: { min: 1.5, max: 8.0 },
    category: "agc",
  },
  "agc.attack_time_ms": {
    id: "agc.attack_time_ms",
    name: "AGC Attack Time",
    description: "Attack time of AGC envelope follower.",
    unit: "ms",
    type: "number",
    validRange: { min: 1, max: 100 },
    recommendedRange: { min: 5, max: 20 },
    aiAdjustmentRange: { min: 1, max: 50 },
    category: "agc",
  },
  "agc.release_time_ms": {
    id: "agc.release_time_ms",
    name: "AGC Release Time",
    description: "Release time of AGC envelope follower.",
    unit: "ms",
    type: "number",
    validRange: { min: 20, max: 1000 },
    recommendedRange: { min: 80, max: 400 },
    aiAdjustmentRange: { min: 50, max: 800 },
    category: "agc",
  },
  "agc.max_gain_db": {
    id: "agc.max_gain_db",
    name: "AGC Max Gain",
    description: "Maximum gain AGC is allowed to apply.",
    unit: "dB",
    type: "number",
    validRange: { min: 0, max: 60 },
    recommendedRange: { min: 10, max: 40 },
    aiAdjustmentRange: { min: 6, max: 50 },
    category: "agc",
  },

  // AEC (4 knobs)
  "aec.enabled": {
    id: "aec.enabled",
    name: "AEC Enabled",
    description: "Enable or disable acoustic echo cancellation.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "aec",
  },
  "aec.suppression_level_db": {
    id: "aec.suppression_level_db",
    name: "AEC Suppression Level",
    description: "Target echo suppression depth.",
    unit: "dB",
    type: "number",
    validRange: { min: -60, max: 0 },
    recommendedRange: { min: -45, max: -20 },
    aiAdjustmentRange: { min: -50, max: -10 },
    category: "aec",
  },
  "aec.tail_length_ms": {
    id: "aec.tail_length_ms",
    name: "AEC Tail Length",
    description: "Maximum echo tail length handled by the AEC.",
    unit: "ms",
    type: "number",
    validRange: { min: 32, max: 1024 },
    recommendedRange: { min: 64, max: 256 },
    aiAdjustmentRange: { min: 64, max: 512 },
    category: "aec",
  },
  "aec.nlp_mode": {
    id: "aec.nlp_mode",
    name: "AEC NLP Mode",
    description: "Non-linear processing aggressiveness for echo residual.",
    unit: "enum",
    type: "enum",
    validValues: ["off", "mild", "moderate", "aggressive"],
    recommendedValues: ["moderate"],
    aiAllowedValues: ["mild", "moderate", "aggressive"],
    category: "aec",
  },

  // NR (3 knobs)
  "nr.enabled": {
    id: "nr.enabled",
    name: "NR Enabled",
    description: "Enable or disable noise reduction stage.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "nr",
  },
  "nr.suppression_level_db": {
    id: "nr.suppression_level_db",
    name: "NR Suppression Level",
    description: "Noise attenuation applied by NR.",
    unit: "dB",
    type: "number",
    validRange: { min: -30, max: 0 },
    recommendedRange: { min: -18, max: -6 },
    aiAdjustmentRange: { min: -24, max: -3 },
    category: "nr",
  },
  "nr.spectral_floor_db": {
    id: "nr.spectral_floor_db",
    name: "NR Spectral Floor",
    description: "Minimum spectral floor to avoid musical noise.",
    unit: "dB",
    type: "number",
    validRange: { min: -90, max: -40 },
    recommendedRange: { min: -80, max: -60 },
    aiAdjustmentRange: { min: -85, max: -55 },
    category: "nr",
  },

  // Compressor (3 knobs)
  "compressor.enabled": {
    id: "compressor.enabled",
    name: "Compressor Enabled",
    description: "Enable or disable dynamic range compressor.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["false", "true"],
    aiAllowedValues: ["false", "true"],
    category: "compressor",
  },
  "compressor.threshold_dbfs": {
    id: "compressor.threshold_dbfs",
    name: "Compressor Threshold",
    description: "Level at which compression starts.",
    unit: "dBFS",
    type: "number",
    validRange: { min: -40, max: 0 },
    recommendedRange: { min: -24, max: -6 },
    aiAdjustmentRange: { min: -30, max: -3 },
    category: "compressor",
  },
  "compressor.ratio": {
    id: "compressor.ratio",
    name: "Compressor Ratio",
    description: "Compression ratio once above threshold.",
    unit: "ratio",
    type: "number",
    validRange: { min: 1.0, max: 20.0 },
    recommendedRange: { min: 2.0, max: 6.0 },
    aiAdjustmentRange: { min: 1.5, max: 10.0 },
    category: "compressor",
  },

  // Limiter (2 knobs)
  "limiter.enabled": {
    id: "limiter.enabled",
    name: "Limiter Enabled",
    description: "Enable or disable output limiter.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "limiter",
  },
  "limiter.threshold_dbfs": {
    id: "limiter.threshold_dbfs",
    name: "Limiter Threshold",
    description: "Peak level ceiling for output limiter.",
    unit: "dBFS",
    type: "number",
    validRange: { min: -12, max: 0 },
    recommendedRange: { min: -6, max: -1 },
    aiAdjustmentRange: { min: -9, max: 0 },
    category: "limiter",
  },

  // EQ (2 knobs)
  "eq.enabled": {
    id: "eq.enabled",
    name: "EQ Enabled",
    description: "Enable or disable EQ filter.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["false", "true"],
    aiAllowedValues: ["false", "true"],
    category: "eq",
  },
  "eq.preset": {
    id: "eq.preset",
    name: "EQ Preset",
    description: "Named EQ preset for voice/audio shaping.",
    unit: "enum",
    type: "enum",
    validValues: ["flat", "voice", "bright", "dark", "custom"],
    recommendedValues: ["voice"],
    aiAllowedValues: ["flat", "voice", "bright", "dark"],
    category: "eq",
  },

  // Buffer (17 knobs)
  "buffer.size_ms": {
    id: "buffer.size_ms",
    name: "Buffer Size",
    description: "Base buffer size for playout/processing.",
    unit: "ms",
    type: "number",
    validRange: { min: 20, max: 2000 },
    recommendedRange: { min: 80, max: 400 },
    aiAdjustmentRange: { min: 40, max: 800 },
    category: "buffer",
  },
  "buffer.jitter_size_ms": {
    id: "buffer.jitter_size_ms",
    name: "Jitter Buffer Size",
    description: "Target size of jitter buffer.",
    unit: "ms",
    type: "number",
    validRange: { min: 0, max: 500 },
    recommendedRange: { min: 20, max: 120 },
    aiAdjustmentRange: { min: 10, max: 200 },
    category: "buffer",
  },
  "buffer.playout_delay_ms": {
    id: "buffer.playout_delay_ms",
    name: "Playout Delay",
    description: "Additional playout delay to smooth jitter.",
    unit: "ms",
    type: "number",
    validRange: { min: 0, max: 500 },
    recommendedRange: { min: 20, max: 120 },
    aiAdjustmentRange: { min: 10, max: 200 },
    category: "buffer",
  },
  "buffer.adaptive_mode": {
    id: "buffer.adaptive_mode",
    name: "Adaptive Buffer",
    description: "Enable adaptive buffer resizing.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "buffer",
  },
  "buffer.min_size_ms": {
    id: "buffer.min_size_ms",
    name: "Min Buffer Size",
    description: "Lower bound for adaptive buffer size.",
    unit: "ms",
    type: "number",
    validRange: { min: 10, max: 200 },
    recommendedRange: { min: 20, max: 80 },
    aiAdjustmentRange: { min: 10, max: 150 },
    category: "buffer",
  },
  "buffer.max_size_ms": {
    id: "buffer.max_size_ms",
    name: "Max Buffer Size",
    description: "Upper bound for adaptive buffer size.",
    unit: "ms",
    type: "number",
    validRange: { min: 100, max: 5000 },
    recommendedRange: { min: 500, max: 2000 },
    aiAdjustmentRange: { min: 300, max: 3000 },
    category: "buffer",
  },
  "buffer.target_level_pct": {
    id: "buffer.target_level_pct",
    name: "Target Buffer Level",
    description: "Target buffer fill level as percentage.",
    unit: "%",
    type: "number",
    validRange: { min: 10, max: 90 },
    recommendedRange: { min: 40, max: 70 },
    aiAdjustmentRange: { min: 30, max: 80 },
    category: "buffer",
  },
  "buffer.underrun_threshold_ms": {
    id: "buffer.underrun_threshold_ms",
    name: "Underrun Threshold",
    description: "Threshold to consider buffer underrun.",
    unit: "ms",
    type: "number",
    validRange: { min: 0, max: 200 },
    recommendedRange: { min: 5, max: 50 },
    aiAdjustmentRange: { min: 2, max: 100 },
    category: "buffer",
  },
  "buffer.overrun_threshold_ms": {
    id: "buffer.overrun_threshold_ms",
    name: "Overrun Threshold",
    description: "Threshold to consider buffer overrun.",
    unit: "ms",
    type: "number",
    validRange: { min: 50, max: 5000 },
    recommendedRange: { min: 200, max: 1500 },
    aiAdjustmentRange: { min: 100, max: 3000 },
    category: "buffer",
  },
  "buffer.growth_rate": {
    id: "buffer.growth_rate",
    name: "Growth Rate",
    description: "Multiplicative growth factor when expanding buffer.",
    unit: "factor",
    type: "number",
    validRange: { min: 1.0, max: 5.0 },
    recommendedRange: { min: 1.2, max: 2.0 },
    aiAdjustmentRange: { min: 1.0, max: 3.0 },
    category: "buffer",
  },
  "buffer.shrink_rate": {
    id: "buffer.shrink_rate",
    name: "Shrink Rate",
    description: "Multiplicative factor when shrinking buffer.",
    unit: "factor",
    type: "number",
    validRange: { min: 0.5, max: 1.0 },
    recommendedRange: { min: 0.8, max: 0.98 },
    aiAdjustmentRange: { min: 0.7, max: 1.0 },
    category: "buffer",
  },
  "buffer.packet_loss_concealment": {
    id: "buffer.packet_loss_concealment",
    name: "Packet Loss Concealment",
    description: "Enable packet loss concealment algorithms.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "buffer",
  },
  "buffer.fec_enabled": {
    id: "buffer.fec_enabled",
    name: "FEC Enabled",
    description: "Enable forward error correction for packets.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["false", "true"],
    aiAllowedValues: ["false", "true"],
    category: "buffer",
  },
  "buffer.interleaving_depth": {
    id: "buffer.interleaving_depth",
    name: "Interleaving Depth",
    description: "Packet interleaving depth for loss robustness.",
    unit: "packets",
    type: "number",
    validRange: { min: 0, max: 10 },
    recommendedRange: { min: 0, max: 4 },
    aiAdjustmentRange: { min: 0, max: 6 },
    category: "buffer",
  },
  "buffer.reorder_tolerance_ms": {
    id: "buffer.reorder_tolerance_ms",
    name: "Reorder Tolerance",
    description: "Time window to accept out-of-order packets.",
    unit: "ms",
    type: "number",
    validRange: { min: 0, max: 200 },
    recommendedRange: { min: 20, max: 80 },
    aiAdjustmentRange: { min: 10, max: 150 },
    category: "buffer",
  },

  // Network/RTP (13 knobs)
  "network.codec": {
    id: "network.codec",
    name: "Network Codec",
    description: "Primary audio codec for RTP stream.",
    unit: "enum",
    type: "enum",
    validValues: ["opus", "pcmu", "pcma", "g722", "g729"],
    recommendedValues: ["opus"],
    aiAllowedValues: ["opus", "pcmu", "pcma"],
    category: "network",
  },
  "network.bitrate_kbps": {
    id: "network.bitrate_kbps",
    name: "Network Bitrate",
    description: "Target codec bitrate.",
    unit: "kbps",
    type: "number",
    validRange: { min: 6, max: 256 },
    recommendedRange: { min: 32, max: 96 },
    aiAdjustmentRange: { min: 24, max: 128 },
    category: "network",
  },
  "network.packet_size_ms": {
    id: "network.packet_size_ms",
    name: "Packet Size",
    description: "RTP packetization interval.",
    unit: "ms",
    type: "number",
    validRange: { min: 10, max: 60 },
    recommendedRange: { min: 20, max: 40 },
    aiAdjustmentRange: { min: 10, max: 60 },
    category: "network",
  },
  "network.dtx_enabled": {
    id: "network.dtx_enabled",
    name: "DTX Enabled",
    description: "Enable discontinuous transmission in silence.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "network",
  },
  "network.vad_mode": {
    id: "network.vad_mode",
    name: "VAD Mode",
    description: "Voice activity detection aggressiveness.",
    unit: "enum",
    type: "enum",
    validValues: ["off", "low", "normal", "aggressive"],
    recommendedValues: ["normal"],
    aiAllowedValues: ["low", "normal", "aggressive"],
    category: "network",
  },
  "network.redundancy_level": {
    id: "network.redundancy_level",
    name: "Redundancy Level",
    description: "Redundant frame count per packet.",
    unit: "frames",
    type: "number",
    validRange: { min: 0, max: 3 },
    recommendedRange: { min: 0, max: 1 },
    aiAdjustmentRange: { min: 0, max: 2 },
    category: "network",
  },
  "network.retransmission_enabled": {
    id: "network.retransmission_enabled",
    name: "Retransmission Enabled",
    description: "Enable RTP retransmission (where supported).",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "network",
  },
  "network.congestion_control": {
    id: "network.congestion_control",
    name: "Congestion Control",
    description: "Congestion control strategy.",
    unit: "enum",
    type: "enum",
    validValues: ["off", "fixed", "adaptive"],
    recommendedValues: ["adaptive"],
    aiAllowedValues: ["fixed", "adaptive"],
    category: "network",
  },
  "network.qos_dscp": {
    id: "network.qos_dscp",
    name: "QoS DSCP",
    description: "DSCP value for QoS marking.",
    unit: "value",
    type: "number",
    validRange: { min: 0, max: 63 },
    recommendedRange: { min: 34, max: 46 },
    aiAdjustmentRange: { min: 26, max: 46 },
    category: "network",
  },
  "network.rtp_timeout_ms": {
    id: "network.rtp_timeout_ms",
    name: "RTP Timeout",
    description: "Timeout with no RTP before call is considered dead.",
    unit: "ms",
    type: "number",
    validRange: { min: 1000, max: 60000 },
    recommendedRange: { min: 4000, max: 20000 },
    aiAdjustmentRange: { min: 2000, max: 30000 },
    category: "network",
  },
  "network.keepalive_interval_ms": {
    id: "network.keepalive_interval_ms",
    name: "Keepalive Interval",
    description: "Interval between keepalive messages.",
    unit: "ms",
    type: "number",
    validRange: { min: 100, max: 60000 },
    recommendedRange: { min: 500, max: 5000 },
    aiAdjustmentRange: { min: 200, max: 10000 },
    category: "network",
  },
  "network.mtu_size": {
    id: "network.mtu_size",
    name: "MTU Size",
    description: "Network MTU used for RTP/UDP packets.",
    unit: "bytes",
    type: "number",
    validRange: { min: 576, max: 1500 },
    recommendedRange: { min: 1200, max: 1500 },
    aiAdjustmentRange: { min: 1000, max: 1500 },
    category: "network",
  },

  // Asterisk (10 knobs)
  "asterisk.echo_cancel": {
    id: "asterisk.echo_cancel",
    name: "Echo Cancel",
    description: "Echo cancellation tail in taps/frames.",
    unit: "samples",
    type: "number",
    validRange: { min: 0, max: 1024 },
    recommendedRange: { min: 32, max: 256 },
    aiAdjustmentRange: { min: 0, max: 512 },
    category: "asterisk",
  },
  "asterisk.silence_threshold": {
    id: "asterisk.silence_threshold",
    name: "Silence Threshold",
    description: "Level below which audio is treated as silence.",
    unit: "level",
    type: "number",
    validRange: { min: 0, max: 1000 },
    recommendedRange: { min: 150, max: 400 },
    aiAdjustmentRange: { min: 100, max: 600 },
    category: "asterisk",
  },
  "asterisk.talk_detect": {
    id: "asterisk.talk_detect",
    name: "Talk Detect",
    description: "Level above which talk is detected.",
    unit: "level",
    type: "number",
    validRange: { min: 0, max: 5000 },
    recommendedRange: { min: 1500, max: 3500 },
    aiAdjustmentRange: { min: 800, max: 4000 },
    category: "asterisk",
  },
  "asterisk.rx_gain": {
    id: "asterisk.rx_gain",
    name: "RX Gain",
    description: "Receive gain applied by Asterisk.",
    unit: "dB",
    type: "number",
    validRange: { min: -20, max: 20 },
    recommendedRange: { min: -3, max: 3 },
    aiAdjustmentRange: { min: -6, max: 6 },
    category: "asterisk",
  },
  "asterisk.tx_gain": {
    id: "asterisk.tx_gain",
    name: "TX Gain",
    description: "Transmit gain applied by Asterisk.",
    unit: "dB",
    type: "number",
    validRange: { min: -20, max: 20 },
    recommendedRange: { min: -3, max: 3 },
    aiAdjustmentRange: { min: -6, max: 6 },
    category: "asterisk",
  },
  "asterisk.jitter_buffer": {
    id: "asterisk.jitter_buffer",
    name: "Jitter Buffer",
    description: "Jitter buffer implementation mode.",
    unit: "enum",
    type: "enum",
    validValues: ["off", "fixed", "adaptive"],
    recommendedValues: ["adaptive"],
    aiAllowedValues: ["fixed", "adaptive"],
    category: "asterisk",
  },
  "asterisk.dtmf_mode": {
    id: "asterisk.dtmf_mode",
    name: "DTMF Mode",
    description: "How DTMF is transported.",
    unit: "enum",
    type: "enum",
    validValues: ["rfc2833", "inband", "sip-info"],
    recommendedValues: ["rfc2833"],
    aiAllowedValues: ["rfc2833", "sip-info"],
    category: "asterisk",
  },
  "asterisk.nat_mode": {
    id: "asterisk.nat_mode",
    name: "NAT Mode",
    description: "NAT traversal configuration for endpoints.",
    unit: "enum",
    type: "enum",
    validValues: ["auto", "force_rport", "comedia", "off"],
    recommendedValues: ["auto"],
    aiAllowedValues: ["auto", "force_rport", "comedia"],
    category: "asterisk",
  },
  "asterisk.call_limit": {
    id: "asterisk.call_limit",
    name: "Call Limit",
    description: "Maximum concurrent calls on this endpoint/context.",
    unit: "count",
    type: "number",
    validRange: { min: 1, max: 1000 },
    recommendedRange: { min: 5, max: 100 },
    aiAdjustmentRange: { min: 1, max: 200 },
    category: "asterisk",
  },
  "asterisk.registration_timeout": {
    id: "asterisk.registration_timeout",
    name: "Registration Timeout",
    description: "SIP registration expiration.",
    unit: "seconds",
    type: "number",
    validRange: { min: 60, max: 86400 },
    recommendedRange: { min: 600, max: 7200 },
    aiAdjustmentRange: { min: 120, max: 14400 },
    category: "asterisk",
  },

  // Gateway (8 knobs)
  "gateway.ws_reconnect_interval_ms": {
    id: "gateway.ws_reconnect_interval_ms",
    name: "WS Reconnect Interval",
    description: "Interval between WebSocket reconnect attempts.",
    unit: "ms",
    type: "number",
    validRange: { min: 100, max: 60000 },
    recommendedRange: { min: 500, max: 5000 },
    aiAdjustmentRange: { min: 200, max: 10000 },
    category: "gateway",
  },
  "gateway.ws_max_reconnects": {
    id: "gateway.ws_max_reconnects",
    name: "WS Max Reconnects",
    description: "Maximum number of reconnect attempts.",
    unit: "count",
    type: "number",
    validRange: { min: 0, max: 100 },
    recommendedRange: { min: 3, max: 20 },
    aiAdjustmentRange: { min: 0, max: 50 },
    category: "gateway",
  },
  "gateway.audio_chunk_size": {
    id: "gateway.audio_chunk_size",
    name: "Audio Chunk Size",
    description: "Audio frame size per WebSocket message.",
    unit: "bytes",
    type: "number",
    validRange: { min: 160, max: 6400 },
    recommendedRange: { min: 320, max: 2048 },
    aiAdjustmentRange: { min: 160, max: 4096 },
    category: "gateway",
  },
  "gateway.sample_rate": {
    id: "gateway.sample_rate",
    name: "Sample Rate",
    description: "Sample rate used by gateway audio stream.",
    unit: "Hz",
    type: "number",
    validRange: { min: 8000, max: 48000 },
    recommendedRange: { min: 16000, max: 24000 },
    aiAdjustmentRange: { min: 8000, max: 48000 },
    category: "gateway",
  },
  "gateway.channels": {
    id: "gateway.channels",
    name: "Channels",
    description: "Number of audio channels.",
    unit: "channels",
    type: "number",
    validRange: { min: 1, max: 8 },
    recommendedRange: { min: 1, max: 2 },
    aiAdjustmentRange: { min: 1, max: 2 },
    category: "gateway",
  },
  "gateway.encoding": {
    id: "gateway.encoding",
    name: "Encoding",
    description: "Audio encoding format on gateway link.",
    unit: "enum",
    type: "enum",
    validValues: ["pcm", "opus", "mulaw", "alaw"],
    recommendedValues: ["pcm"],
    aiAllowedValues: ["pcm", "opus"],
    category: "gateway",
  },
  "gateway.stream_timeout_ms": {
    id: "gateway.stream_timeout_ms",
    name: "Stream Timeout",
    description: "Inactivity timeout for media stream.",
    unit: "ms",
    type: "number",
    validRange: { min: 1000, max: 600000 },
    recommendedRange: { min: 30000, max: 180000 },
    aiAdjustmentRange: { min: 10000, max: 300000 },
    category: "gateway",
  },
  "gateway.debug_mode": {
    id: "gateway.debug_mode",
    name: "Debug Mode",
    description: "Enable verbose debug logging in gateway.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["false"],
    aiAllowedValues: ["false", "true"],
    category: "gateway",
  },

  // Deepgram (12 knobs)
  "deepgram.model": {
    id: "deepgram.model",
    name: "Deepgram Model",
    description: "Deepgram model identifier.",
    unit: "enum",
    type: "enum",
    validValues: ["nova-2", "nova-2-meeting", "nova-2-phone", "enhance-general"],
    recommendedValues: ["nova-2"],
    aiAllowedValues: ["nova-2", "nova-2-meeting", "nova-2-phone", "enhance-general"],
    category: "deepgram",
  },
  "deepgram.language": {
    id: "deepgram.language",
    name: "Language",
    description: "Language code for transcription.",
    unit: "string",
    type: "enum",
    validValues: ["en", "en-US", "es", "ja", "fr", "de"],
    recommendedValues: ["en-US"],
    aiAllowedValues: ["en", "en-US", "es", "ja", "fr", "de"],
    category: "deepgram",
  },
  "deepgram.punctuate": {
    id: "deepgram.punctuate",
    name: "Punctuate",
    description: "Add punctuation to transcription.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "deepgram",
  },
  "deepgram.profanity_filter": {
    id: "deepgram.profanity_filter",
    name: "Profanity Filter",
    description: "Mask or filter profanities.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "deepgram",
  },
  "deepgram.redact": {
    id: "deepgram.redact",
    name: "Redact",
    description: "Redact sensitive entities.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "deepgram",
  },
  "deepgram.diarize": {
    id: "deepgram.diarize",
    name: "Diarize",
    description: "Enable multi-speaker diarization.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["false"],
    aiAllowedValues: ["false", "true"],
    category: "deepgram",
  },
  "deepgram.smart_format": {
    id: "deepgram.smart_format",
    name: "Smart Format",
    description: "Apply smart formatting (dates, numbers, etc.).",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "deepgram",
  },
  "deepgram.interim_results": {
    id: "deepgram.interim_results",
    name: "Interim Results",
    description: "Enable streaming interim ASR results.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "deepgram",
  },
  "deepgram.endpointing": {
    id: "deepgram.endpointing",
    name: "Endpointing",
    description: "Endpointing timeout after speech to close segment.",
    unit: "ms",
    type: "number",
    validRange: { min: 0, max: 2000 },
    recommendedRange: { min: 200, max: 800 },
    aiAdjustmentRange: { min: 100, max: 1500 },
    category: "deepgram",
  },
  "deepgram.vad_turnoff": {
    id: "deepgram.vad_turnoff",
    name: "VAD Turnoff",
    description: "VAD-based timeout to turn off stream on long silence.",
    unit: "ms",
    type: "number",
    validRange: { min: 0, max: 2000 },
    recommendedRange: { min: 300, max: 900 },
    aiAdjustmentRange: { min: 100, max: 1500 },
    category: "deepgram",
  },

  // Translation (9 knobs)
  "translation.source_lang": {
    id: "translation.source_lang",
    name: "Source Language",
    description: "Source language code.",
    unit: "string",
    type: "enum",
    validValues: ["en", "es", "fr", "de", "ja", "zh"],
    recommendedValues: ["en"],
    aiAllowedValues: ["en", "es", "fr", "de", "ja", "zh"],
    category: "translation",
  },
  "translation.target_lang": {
    id: "translation.target_lang",
    name: "Target Language",
    description: "Target language code.",
    unit: "string",
    type: "enum",
    validValues: ["en", "es", "fr", "de", "ja", "zh"],
    recommendedValues: ["es"],
    aiAllowedValues: ["en", "es", "fr", "de", "ja", "zh"],
    category: "translation",
  },
  "translation.formality": {
    id: "translation.formality",
    name: "Formality",
    description: "Formality level of translation.",
    unit: "enum",
    type: "enum",
    validValues: ["default", "more", "less"],
    recommendedValues: ["default"],
    aiAllowedValues: ["default", "more", "less"],
    category: "translation",
  },
  "translation.preserve_formatting": {
    id: "translation.preserve_formatting",
    name: "Preserve Formatting",
    description: "Preserve original formatting and casing.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "translation",
  },
  "translation.glossary_id": {
    id: "translation.glossary_id",
    name: "Glossary ID",
    description: "Optional glossary identifier.",
    unit: "string",
    type: "enum",
    validValues: ["null", "glossary_1", "glossary_2"],
    recommendedValues: ["null"],
    aiAllowedValues: ["null", "glossary_1"],
    category: "translation",
  },
  "translation.max_length": {
    id: "translation.max_length",
    name: "Max Length",
    description: "Maximum characters per translation request.",
    unit: "chars",
    type: "number",
    validRange: { min: 1, max: 30000 },
    recommendedRange: { min: 100, max: 8000 },
    aiAdjustmentRange: { min: 50, max: 12000 },
    category: "translation",
  },
  "translation.timeout_ms": {
    id: "translation.timeout_ms",
    name: "Timeout",
    description: "Timeout for translation API call.",
    unit: "ms",
    type: "number",
    validRange: { min: 100, max: 30000 },
    recommendedRange: { min: 500, max: 8000 },
    aiAdjustmentRange: { min: 300, max: 15000 },
    category: "translation",
  },
  "translation.cache_enabled": {
    id: "translation.cache_enabled",
    name: "Cache Enabled",
    description: "Enable translation result caching.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "translation",
  },

  // TTS (9 knobs)
  "tts.voice_id": {
    id: "tts.voice_id",
    name: "Voice ID",
    description: "TTS voice identifier.",
    unit: "enum",
    type: "enum",
    validValues: ["rachel", "josh", "adam", "bella"],
    recommendedValues: ["rachel"],
    aiAllowedValues: ["rachel", "josh", "adam", "bella"],
    category: "tts",
  },
  "tts.stability": {
    id: "tts.stability",
    name: "Stability",
    description: "Stability vs. variability of TTS output.",
    unit: "float",
    type: "number",
    validRange: { min: 0.0, max: 1.0 },
    recommendedRange: { min: 0.3, max: 0.8 },
    aiAdjustmentRange: { min: 0.1, max: 0.9 },
    category: "tts",
  },
  "tts.similarity_boost": {
    id: "tts.similarity_boost",
    name: "Similarity Boost",
    description: "How strongly to match reference voice timbre.",
    unit: "float",
    type: "number",
    validRange: { min: 0.0, max: 1.0 },
    recommendedRange: { min: 0.5, max: 0.9 },
    aiAdjustmentRange: { min: 0.2, max: 1.0 },
    category: "tts",
  },
  "tts.style": {
    id: "tts.style",
    name: "Style",
    description: "Global speaking style parameter.",
    unit: "float",
    type: "number",
    validRange: { min: -2.0, max: 2.0 },
    recommendedRange: { min: -1.0, max: 1.0 },
    aiAdjustmentRange: { min: -2.0, max: 2.0 },
    category: "tts",
  },
  "tts.use_speaker_boost": {
    id: "tts.use_speaker_boost",
    name: "Speaker Boost",
    description: "Enable speaker boost / presence enhancement.",
    unit: "boolean",
    type: "boolean",
    validValues: ["false", "true"],
    recommendedValues: ["true"],
    aiAllowedValues: ["false", "true"],
    category: "tts",
  },
  "tts.model": {
    id: "tts.model",
    name: "Model",
    description: "TTS model identifier.",
    unit: "enum",
    type: "enum",
    validValues: ["eleven_monolingual_v1", "eleven_multilingual_v2", "fast-v1"],
    recommendedValues: ["eleven_monolingual_v1"],
    aiAllowedValues: ["eleven_monolingual_v1", "eleven_multilingual_v2", "fast-v1"],
    category: "tts",
  },
  "tts.optimize_streaming_latency": {
    id: "tts.optimize_streaming_latency",
    name: "Streaming Latency",
    description: "Latency optimization level for streaming TTS.",
    unit: "preset",
    type: "number",
    validRange: { min: 0, max: 4 },
    recommendedRange: { min: 1, max: 3 },
    aiAdjustmentRange: { min: 0, max: 4 },
    category: "tts",
  },
  "tts.output_format": {
    id: "tts.output_format",
    name: "Output Format",
    description: "Audio output format for TTS.",
    unit: "enum",
    type: "enum",
    validValues: ["pcm_16000", "pcm_22050", "mp3_44100", "ogg_vorbis"],
    recommendedValues: ["pcm_16000"],
    aiAllowedValues: ["pcm_16000", "pcm_22050", "mp3_44100"],
    category: "tts",
  },
}

export const KNOBS_CATALOG: KnobDefinition[] = Object.values(KNOB_DEFINITIONS)

export function getKnobsByCategory(category: KnobDefinition["category"]): KnobDefinition[] {
  return KNOBS_CATALOG.filter((knob) => knob.category === category)
}
